#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
Generate the live map's geographic LED coordinates for metro.htm from the
board's LED numbering PDF (LED-Numbering.pdf, exported from the PCB layout).

Not part of the firmware build. Standard library only. Run by hand after the
PDF changes:

    python gen_map_coords.py

How it works: the PDF places one text label per LED, named after the line and
the LED's index along that line's strip (RD0..RD266, BL0..BL297, GR0..GR180,
OR0..OR208, YL0..YL184) - the same line-local indices the usermod's /asl/live
endpoint reports. Each label is a text object with an explicit position
("1 0 0 -1 x y Tm" in the page's y-down coordinate system) whose characters
are mapped through the font's ToUnicode table. The script reads every label,
takes its approximate centre as the LED position, checks that every line is
complete (no missing or duplicate indices), and replaces the
"const COORDS = ...;" line in metro.htm.

It also collects the board's grey artwork (the map backdrop: outline, rivers,
county lines, track corridors, station pads) - every path filled while the
fill colour is grey - and writes it as SVG path data into the
"const BACKDROP = ...;" line, in the same coordinates as the LEDs. The
station bullseyes in that artwork (circles) go into "const BULLSEYES = ...;"
as [x, y, radius]; the page puts its station hover targets there.

Optional: if wmata_stations.json (WMATA's station list, the response of
https://api.wmata.com/Rail.svc/json/jStations saved as a file) is next to this
script, its station codes and names go into "const DEST_NAMES = ...;" so train
tooltips show destination names instead of codes.
"""

import json
import math
import os
import re
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
PDF = os.path.join(HERE, 'LED-Numbering.pdf')
HTML = os.path.join(HERE, 'metro.htm')
STATIONS = os.path.join(HERE, 'wmata_stations.json')
LINE_LEDS = {'RD': 267, 'BL': 298, 'GR': 181, 'OR': 209, 'YL': 185}  # must match the map tables


def read_streams():
  raw = open(PDF, 'rb').read()
  streams = [m.group(1) for m in re.finditer(rb'stream\r?\n(.*?)\r?\nendstream', raw, re.S)]
  content, cmap_text = None, None
  for s in streams:
    try:
      d = zlib.decompress(s).decode('latin-1')
    except zlib.error:
      continue
    if 'beginbfchar' in d:
      cmap_text = d
    elif ' TJ' in d and content is None:
      content = d
  if content is None or cmap_text is None:
    sys.exit('could not find the page content or the font map in the PDF')
  return content, cmap_text


def read_labels(content, cmap_text):
  cmap = {int(a, 16): chr(int(b, 16)) for a, b in re.findall(r'<([0-9A-F]{4})> <([0-9A-F]{4})>', cmap_text)}

  labels = {}
  pattern = r'BT\s+[-\d.]+ [-\d.]+ [-\d.]+ [-\d.]+ ([-\d.]+) ([-\d.]+) Tm.*?/F\d+ ([\d.]+) Tf\s*\[(.*?)\] TJ'
  for m in re.finditer(pattern, content, re.S):
    x, y, size = map(float, m.groups()[:3])
    text = ''.join(cmap.get(int(h[i:i + 4], 16), '?')
                   for h in re.findall(r'<([0-9A-F]+)>', m.group(4)) for i in range(0, len(h), 4))
    if re.fullmatch(r'(RD|BL|GR|OR|YL)\d+', text):
      if text in labels:
        sys.exit(f'duplicate label {text}')
      # (x, y) is the start of the baseline: shift to the label's approximate centre
      labels[text] = (x + len(text) * size * 0.28, y - size * 0.35)
  return labels


GREY = 0.745  # fill colour of the backdrop artwork (0.74509803 = 190/255)


def read_backdrop(content):
  """SVG path data of every path filled in grey. The page only uses m/l/c/h
  path operators and 'f' (nonzero) fills, with no transforms, so PDF
  coordinates map straight onto the LED coordinates."""
  num = lambda v: f'{float(v):.1f}'.rstrip('0').rstrip('.')
  body = re.sub(r'\bBT\b.*?\bET\b', ' ', content, flags=re.S)  # drop the text labels
  fill, args, path, out, count = None, [], [], [], 0
  for tok in re.findall(r'/\S+|[-\d.]+|[A-Za-z*\']+', body):
    if re.fullmatch(r'[-\d.]+', tok):
      args.append(tok)
      continue
    if tok in ('sc', 'scn', 'rg', 'g') and args:
      fill = [float(a) for a in args]
    elif tok == 'm':
      path.append('M' + ' '.join(map(num, args[-2:])))
    elif tok == 'l':
      path.append('L' + ' '.join(map(num, args[-2:])))
    elif tok == 'c':
      path.append('C' + ' '.join(map(num, args[-6:])))
    elif tok == 'h':
      path.append('Z')
    elif tok in ('f', 'F', 'f*', 'S', 's', 'B', 'B*', 'b', 'b*', 'n'):
      if tok in ('f', 'F') and fill and all(abs(v - GREY) < 0.01 for v in fill):
        out.extend(path)
        count += 1
      path = []
    args = []
  return ''.join(out), count


def find_bullseyes(backdrop):
  """[x, y, r] of every station bullseye in the backdrop: circles (closed
  subpaths of only curves with a square bounding box) of radius >= 5, merging
  the concentric rings and dots of one bullseye into its outermost circle."""
  circles = []
  for sub in re.findall(r'M[^M]*', backdrop):
    if 'L' in sub or sub.count('C') < 4:
      continue
    n = [float(v) for v in re.findall(r'-?[\d.]+', sub)]
    xs, ys = n[0::2], n[1::2]
    w, h = max(xs) - min(xs), max(ys) - min(ys)
    if abs(w - h) < 0.15 * max(w, h) and w / 2 >= 5:
      circles.append(((max(xs) + min(xs)) / 2, (max(ys) + min(ys)) / 2, w / 2))
  out = []
  for c in sorted(circles, key=lambda c: -c[2]):
    if not any(math.hypot(c[0] - o[0], c[1] - o[1]) < 4 for o in out):
      out.append(c)
  return [[round(v, 1) for v in c] for c in out]


def main():
  content, cmap_text = read_streams()
  labels = read_labels(content, cmap_text)
  coords = {}
  for line, n in LINE_LEDS.items():
    missing = [i for i in range(n) if f'{line}{i}' not in labels]
    if missing:
      sys.exit(f'{line}: missing labels for LEDs {missing[:20]}')
    extra = [k for k in labels if k.startswith(line) and int(k[2:]) >= n]
    if extra:
      sys.exit(f'{line}: labels beyond the line length: {extra[:10]}')
    coords[line] = [[round(labels[f'{line}{i}'][0], 1), round(labels[f'{line}{i}'][1], 1)] for i in range(n)]
    print(f'{line}: {n} LEDs')

  html = open(HTML, encoding='utf-8').read()
  new_line = 'const COORDS = ' + json.dumps(coords, separators=(',', ':')) + ';'
  html, count = re.subn(r'^const COORDS = .*?;$', lambda _: new_line, html, count=1, flags=re.M)
  if count != 1:
    sys.exit('could not find the "const COORDS = ...;" line in metro.htm')

  backdrop, shapes = read_backdrop(content)
  new_line = 'const BACKDROP = ' + json.dumps(backdrop) + ';'
  html, count = re.subn(r'^const BACKDROP = .*?;$', lambda _: new_line, html, count=1, flags=re.M)
  if count != 1:
    sys.exit('could not find the "const BACKDROP = ...;" line in metro.htm')

  bullseyes = find_bullseyes(backdrop)
  new_line = 'const BULLSEYES = ' + json.dumps(bullseyes, separators=(',', ':')) + ';'
  html, count = re.subn(r'^const BULLSEYES = .*?;$', lambda _: new_line, html, count=1, flags=re.M)
  if count != 1:
    sys.exit('could not find the "const BULLSEYES = ...;" line in metro.htm')
  print(f'{len(bullseyes)} station bullseyes')

  if os.path.exists(STATIONS):
    stations = json.load(open(STATIONS, encoding='utf-8')).get('Stations', [])
    names = {s['Code']: s['Name'] for s in stations if s.get('Code') and s.get('Name')}
    if not names:
      sys.exit(f'no "Stations" with Code and Name in {os.path.basename(STATIONS)}')
    new_line = 'const DEST_NAMES = ' + json.dumps(names, separators=(',', ':'), ensure_ascii=False) + ';'
    html, count = re.subn(r'^const DEST_NAMES = .*?;$', lambda _: new_line, html, count=1, flags=re.M)
    if count != 1:
      sys.exit('could not find the "const DEST_NAMES = ...;" line in metro.htm')
    print(f'{len(names)} destination names')

  open(HTML, 'w', encoding='utf-8', newline='\n').write(html)
  print(f'wrote {sum(LINE_LEDS.values())} LED positions and {shapes} backdrop shapes '
        f'({len(backdrop) // 1024} KB) into {os.path.basename(HTML)}')


if __name__ == '__main__':
  main()
# AI: end
