#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
Consistency checker for the ASL_v2 map and timing tables.

Not part of the firmware build. Run it by hand after editing asl_map_data.h or
regenerating asl_timing_data.h:

    python usermods/ASL_v2/timing/check_map.py

It parses the C++ tables directly (standard library only) and checks:
  1. structure: domain/station/LED counts, reversed domains, circuits listed in
     two domains, station circuits that sit inside a domain (passing trains
     would snap onto the station dot)
  2. LED layout: every station dot sits in the one-LED gap between its
     neighbouring LED ranges
  3. shared track: lines riding the same stretch use the same circuits on the
     same track (known, accepted differences are listed in ACCEPTED below)
  4. timing sanity: seconds per circuit for every measured domain, flagging
     values far from the system median
  5. a mirror of the firmware's sim (rackTimetables / offlineSimTrains plus the
     renderer's circuit -> LED lookup): every train must start and finish at
     the right end, always map to an LED, and never step backwards

Exit status is 1 if any ERROR is reported, 0 otherwise (warnings allowed).
"""

import os
import re
import statistics
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_timing  # station name lists per line, in Track1 order

MAP_H = os.path.join(HERE, '..', 'asl_map_data.h')
TIMING_H = os.path.join(HERE, '..', 'asl_timing_data.h')
LINES = ['Red', 'Blue', 'Green', 'Orange', 'Yellow']
FALLBACK_DWELL_S = 25          # firmware default (DEF_DWELL_S)
PLACEHOLDER_S_PER_CIRCUIT = 3  # firmware ASL_PLACEHOLDER_S_PER_CIRCUIT

# Shared-track differences that are known and deliberately kept as recorded
# (see the comments in asl_map_data.h). Keys: (station or frozenset of the two
# stations of a segment, line). Anything not listed here is reported.
ACCEPTED = {
  # Orange joins the Blue track at Rosslyn with its own numbering
  ('Rosslyn', 'Orange'), (frozenset(('Rosslyn', 'Foggy Bottom-GWU')), 'Orange'),
  # unresolved: platform circuit disagrees between Orange and Blue
  ('Stadium-Armory', 'Orange'), (frozenset(('Potomac Ave', 'Stadium-Armory')), 'Orange'),
  # Yellow uses the junction circuit where it meets the bridge / Eisenhower branch
  ('Pentagon', 'Yellow'), (frozenset(('Pentagon', 'Pentagon City')), 'Yellow'),
  ("L'Enfant Plaza", 'Yellow'), (frozenset(("L'Enfant Plaza", 'Archives-Navy Memorial')), 'Yellow'),
  ('King St-Old Town', 'Yellow'), (frozenset(('King St-Old Town', 'Braddock Road')), 'Yellow'),
}

# Transfer stations where lines stop at separate platforms (different levels),
# so their circuits are not expected to match across groups. Red is always
# separate and is skipped entirely.
SEPARATE_PLATFORMS = {
  "L'Enfant Plaza": [{'Blue', 'Orange'}, {'Green', 'Yellow'}],
}

errors = []
warnings = []


def err(msg):
  errors.append(msg)
  print('  ERROR', msg)


def warn(msg):
  warnings.append(msg)
  print('  warn ', msg)


def table(src, name):
  m = re.search(r'\b' + re.escape(name) + r'\s*\[\](?:\[2\])?\s*=\s*\{(.*?)\};', src, re.S)
  if not m:
    raise SystemExit(f'table {name} not found')
  body = re.sub(r'//[^\n]*', '', m.group(1))
  return [int(x) for x in re.findall(r'\d+', body)]


def pairs(a):
  return list(zip(a[::2], a[1::2]))


def load():
  mp = open(MAP_H, encoding='utf-8').read()
  tm = open(TIMING_H, encoding='utf-8').read()
  data = {}
  for L in LINES:
    data[L] = {
      'dom': {t: pairs(table(mp, f'{L}LineTrack{t}Domains')) for t in (1, 2)},
      'st': {t: table(mp, f'{L}LineTrack{t}StationSegments') for t in (1, 2)},
      'led': pairs(table(mp, f'{L}LineLEDArray')),
      'pos': table(mp, f'{L}LineStationLEDPosition'),
      'travel': table(tm, f'{L}LineTravelS'),
      'dwell': table(tm, f'{L}LineDwellS'),
      'names': gen_timing.LINES[L],
    }
  return data


def check_structure(data):
  print('1. structure')
  for L, d in data.items():
    n = len(d['pos'])
    if len(d['names']) != n:
      err(f'{L}: {len(d["names"])} station names in gen_timing.py vs {n} station LEDs')
    for t in (1, 2):
      dom, st = d['dom'][t], d['st'][t]
      if len(dom) != len(d['led']) or len(st) != n or n != len(dom) + 1:
        err(f'{L} T{t}: domains {len(dom)}, stations {len(st)}, LED ranges {len(d["led"])}, station LEDs {n}')
      seen = defaultdict(list)
      for y, (a, b) in enumerate(dom):
        if a > b:
          err(f'{L} T{t} domain {y} reversed {a, b}')
        for c in range(min(a, b), max(a, b) + 1):
          seen[c].append(y)
      dup = sorted(c for c, ys in seen.items() if len(ys) > 1)
      if dup:
        err(f'{L} T{t}: circuits in two domains {dup[:10]}')
      for k, c in enumerate(st):
        if c in seen:
          err(f'{L} T{t} station {k} {d["names"][k]}: circuit {c} is inside domain {seen[c]}')


def check_leds(data):
  print('2. LED layout')
  for L, d in data.items():
    led, pos = d['led'], d['pos']
    if pos[0] != 0:
      err(f'{L}: first station LED is {pos[0]}, expected 0')
    for y, (a, b) in enumerate(led):
      if a > b:
        err(f'{L}: LED range {y} reversed {a, b}')
    for k, p in enumerate(pos):
      if k > 0 and p != led[k - 1][1] + 1:
        err(f'{L} station {k} {d["names"][k]}: LED {p} not right after range {led[k - 1]}')
      if k < len(led) and p != led[k][0] - 1:
        err(f'{L} station {k} {d["names"][k]}: LED {p} not right before range {led[k]}')
    print(f'  {L}: {pos[-1] + 1} LEDs')


def check_shared(data):
  print('3. shared track')
  where = defaultdict(list)
  for L, d in data.items():
    for k, nm in enumerate(d['names']):
      groups = SEPARATE_PLATFORMS.get(nm, [])
      level = next((i for i, g in enumerate(groups) if L in g), 0)
      where[(nm, level)].append((L, k))
  where = {key[0] if key[1] == 0 else f'{key[0]} (platform {key[1] + 1})': v for key, v in where.items()}
  for nm, lst in where.items():
    if len(lst) < 2:
      continue
    ref = None
    for L, k in lst:
      v = (data[L]['st'][1][k], data[L]['st'][2][k])
      if L == 'Red':
        continue  # Red has its own platforms at transfer stations
      if ref is None:
        ref = (L, v)
      elif v != ref[1] and (nm.split(' (platform')[0], L) not in ACCEPTED:
        warn(f'{nm}: {L} T1/T2 {v} vs {ref[0]} {ref[1]}')
  segs = defaultdict(list)
  for L, d in data.items():
    for y in range(len(d['dom'][1])):
      segs[frozenset((d['names'][y], d['names'][y + 1]))].append((L, y))
  for key, lst in segs.items():
    if len(lst) < 2:
      continue
    L0, y0 = lst[0]
    v0 = (data[L0]['dom'][1][y0], data[L0]['dom'][2][y0])
    for L, y in lst[1:]:
      v = (data[L]['dom'][1][y], data[L]['dom'][2][y])
      if v != v0 and (key, L) not in ACCEPTED and (key, L0) not in ACCEPTED:
        warn(f'{" -> ".join(sorted(key))}: {L} {v} vs {L0} {v0}')


def check_speed(data):
  print('4. timing sanity (seconds per circuit, measured domains)')
  rows = []
  for L, d in data.items():
    for y, (a, b) in enumerate(d['dom'][1]):
      if d['travel'][y]:
        rows.append((d['travel'][y] / (abs(b - a) + 1), L, d['names'][y], d['names'][y + 1]))
  med = statistics.median(r[0] for r in rows)
  print(f'  median {med:.1f} s/circuit over {len(rows)} domains')
  for spc, L, a, b in sorted(rows):
    if spc > med * 2.2 or spc < med / 2.2:
      warn(f'{L} {a} -> {b}: {spc:.1f} s/circuit')


def target_led(d, c):
  """Mirror of aslTargetLED: station snap (+/-1) then domain interpolation, both tracks."""
  for t in (1, 2):
    for k, s in enumerate(d['st'][t]):
      if abs(c - s) <= 1:
        return d['pos'][k]
    for y, (c0, c1) in enumerate(d['dom'][t]):
      if c0 <= c <= c1:
        l0, l1 = d['led'][y]
        return l0 + (c - c0) * (l1 - l0) / (c1 - c0) if c1 > c0 else 0.5 * (l0 + l1)
  return None


def check_sim(data):
  print(f'5. sim mirror (fallback dwell {FALLBACK_DWELL_S} s)')
  for L, d in data.items():
    phases, acc = [], 0
    n = len(d['pos'])
    for k in range(n):
      acc += d['dwell'][k] or FALLBACK_DWELL_S
      phases.append(acc)
      if k < n - 1:
        a, b = d['dom'][1][k]
        acc += d['travel'][k] or (abs(b - a) + 1) * PLACEHOLDER_S_PER_CIRCUIT
        phases.append(acc)
    run = acc
    for t in (1, 2):
      prev = first = None
      unmapped = backward = 0
      maxjump = 0.0
      for tt in range(1, run):
        s = tt if t == 1 else run - tt
        p = 0
        while p < len(phases) - 1 and s > phases[p]:
          p += 1
        p0 = phases[p - 1] if p else 0
        ln = phases[p] - p0
        if p % 2 == 0:
          c = d['st'][t][p // 2]
        else:
          c0, c1 = d['dom'][t][p // 2]
          c = c0 + ((s - p0) / ln if ln else 0) * (c1 - c0)
        x = target_led(d, c)
        if x is None:
          unmapped += 1
          continue
        if first is None:
          first = x
        if prev is not None:
          step = x - prev
          if (t == 1 and step < -0.01) or (t == 2 and step > 0.01):
            backward += 1
          maxjump = max(maxjump, abs(step))
        prev = x
      end_ok = (first, prev) == ((0, d['pos'][-1]) if t == 1 else (d['pos'][-1], 0))
      print(f'  {L:6s} T{t}: run {run} s ({run / 60:.1f} min), LED {first} -> {prev}, '
            f'max step {maxjump:.2f} LED/s')
      if unmapped:
        err(f'{L} T{t}: {unmapped} s of the run map to no LED')
      if backward:
        err(f'{L} T{t}: {backward} backward steps')
      if not end_ok:
        err(f'{L} T{t}: run goes LED {first} -> {prev}, expected the opposite ends')


def main():
  data = load()
  check_structure(data)
  check_leds(data)
  check_shared(data)
  check_speed(data)
  check_sim(data)
  print(f'\n{len(errors)} error(s), {len(warnings)} warning(s)')
  sys.exit(1 if errors else 0)


if __name__ == '__main__':
  main()
# AI: end
