#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
Generate ../asl_timing_data.h from segment_times.csv.

Not part of the firmware build: run it by hand after editing the CSV, then
commit the regenerated header. Standard library only.

    python gen_timing.py

CSV format (one row per station or segment, in the running order you rode):
  line      tab name from the original workbook (Red, Orange, Blue, ...)
  seq       row order within that line
  kind      station = dwell, doors open to doors closed
            segment = travel, doors closed to doors open at the next station;
                      `name` is the station the segment arrives at
  pass1-3   stopwatch digits as displayed: 135 = 1 min 35 s (seconds 00-59)
  exclude   space-separated pass numbers to ignore (outliers, mis-laps)
  note      free text: why something was excluded, "same track as ...", etc.

Processing rules:
  - Every station and every station-to-station segment is pooled across all
    tabs that ride it (shared track), so each gets one averaged value.
    Pass sets that are exact duplicates of another tab's row are treated as
    copies and counted once. The Silver tab is ignored (not on this hardware).
  - The value used is the plain average of the remaining passes, rounded to
    whole seconds.
  - Stations missing from this hardware revision (Potomac Yard) are folded
    into the surrounding segment: travel in + dwell + travel out.
  - A missing value is written as 0. The firmware substitutes the "Fallback
    Station Dwell" setting for a 0 dwell, and the legacy 3 s/circuit
    placeholder speed for a 0 travel time.

Output arrays are in the firmware's Track1 order (see asl_map_data.h), which
is the measured running order for every line except Green: Green Track1 runs
Branch Ave -> Greenbelt, the opposite of how it was timed, so its lists are
reversed here. Track2 reuses the same values in reverse in the firmware.
"""

import csv
import os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(HERE, 'segment_times.csv')
OUT_PATH = os.path.join(HERE, '..', 'asl_timing_data.h')

IGNORED_TABS = {'Silver'}        # not on this hardware revision
SKIPPED_STATIONS = {'Potomac Yard'}  # not on this hardware revision; folded into its segment

# Station order per firmware line, in Track1 direction. Must match the order of
# <Line>LineTrack1StationSegments / <Line>LineStationLEDPosition.
LINES = {
  'Red': ['Shady Grove', 'Rockville', 'Twinbrook', 'North Bethesda', 'Grosvenor-Strathmore',
          'Medical Center', 'Bethesda', 'Friendship Heights', 'Tenleytown-AU', 'Van Ness-UDC',
          'Cleveland Park', 'Woodley Park-Zoo', 'Dupont Circle', 'Farragut North', 'Metro Center',
          'Gallery Place-Chinatown', 'Judiciary Square', 'Union Station', 'NoMa-Gallaudet U',
          'Rhode Island Ave-Brentwood', 'Brookland-CUA', 'Fort Totten', 'Takoma', 'Silver Spring',
          'Forest Glen', 'Wheaton', 'Glenmont'],
  'Blue': ['Franconia-Springfield', 'Van Dorn Street', 'King St-Old Town', 'Braddock Road',
           'Reagan National Airport', 'Crystal City', 'Pentagon City', 'Pentagon',
           'Arlington Cemetery', 'Rosslyn', 'Foggy Bottom-GWU', 'Farragut West', 'McPherson Square',
           'Metro Center', 'Federal Triangle', 'Smithsonian', "L'Enfant Plaza", 'Federal Center SW',
           'Capitol South', 'Eastern Market', 'Potomac Ave', 'Stadium-Armory', 'Benning Road',
           'Capitol Heights', 'Addison Road-Seat Pleasant', 'Morgan Boulevard', 'Downtown Largo'],
  # Green Track1 = Branch Ave -> Greenbelt (reverse of the measured direction)
  'Green': ['Branch Avenue', 'Suitland', 'Naylor Road', 'Southern Avenue', 'Congress Heights',
            'Anacostia', 'Navy Yard-Ballpark', 'Waterfront', "L'Enfant Plaza",
            'Archives-Navy Memorial', 'Gallery Place-Chinatown', 'Mt Vernon Sq-7th St',
            'Shaw-Howard U', 'U Street/Cardozo', 'Columbia Heights', 'Georgia Ave-Petworth',
            'Fort Totten', 'West Hyattsville', 'Hyattsville Crossing', 'College Park-U of Md',
            'Greenbelt'],
  'Orange': ['Vienna/Fairfax-GMU', 'Dunn Loring-Merrifield', 'West Falls Church',
             'East Falls Church', 'Ballston-MU', 'Virginia Square-GMU', 'Clarendon', 'Court House',
             'Rosslyn', 'Foggy Bottom-GWU', 'Farragut West', 'McPherson Square', 'Metro Center',
             'Federal Triangle', 'Smithsonian', "L'Enfant Plaza", 'Federal Center SW',
             'Capitol South', 'Eastern Market', 'Potomac Ave', 'Stadium-Armory', 'Minnesota Ave',
             'Deanwood', 'Cheverly', 'Landover', 'New Carrollton'],
  # Yellow on this hardware runs Huntington -> Fort Totten (old route north of
  # Mt Vernon Sq); the north end reuses Green's measurements.
  'Yellow': ['Huntington', 'Eisenhower Avenue', 'King St-Old Town', 'Braddock Road',
             'Reagan National Airport', 'Crystal City', 'Pentagon City', 'Pentagon',
             "L'Enfant Plaza", 'Archives-Navy Memorial', 'Gallery Place-Chinatown',
             'Mt Vernon Sq-7th St', 'Shaw-Howard U', 'U Street/Cardozo', 'Columbia Heights',
             'Georgia Ave-Petworth', 'Fort Totten'],
}


def stopwatch_to_s(digits):
  v = int(digits)
  if v % 100 > 59:
    raise ValueError(f'seconds part must be 00-59: {digits}')
  return (v // 100) * 60 + v % 100


def load():
  """Pool passes per station name and per unordered station pair."""
  pools = defaultdict(dict)  # key -> {pass tuple: [tabs]}
  with open(CSV_PATH, newline='', encoding='utf-8') as f:
    rows = sorted(csv.DictReader(f), key=lambda r: (r['line'], int(r['seq'])))
  prev = None
  last_line = None
  for r in rows:
    if r['line'] != last_line:
      prev, last_line = None, r['line']
    if r['line'] in IGNORED_TABS:
      continue
    excl = set(r['exclude'].split())
    passes = tuple(stopwatch_to_s(r[f'pass{i}']) for i in (1, 2, 3)
                   if r[f'pass{i}'].strip() and str(i) not in excl)
    name = r['name'].strip()
    if r['kind'] == 'station':
      key = ('station', name)
      prev = name
    else:
      if prev is None:
        raise ValueError(f"{r['line']} seq {r['seq']}: segment before any station")
      key = ('segment', frozenset((prev, name)))
    if passes:
      pools[key].setdefault(passes, []).append(r['line'])
  return pools


def avg(pools, key):
  """Average of all distinct pass sets for key; None if no data."""
  vals = [v for p in pools.get(key, {}) for v in p]
  return round(sum(vals) / len(vals)) if vals else None


def build(pools, stations):
  """Return (travel per domain, dwell per station) with 0 = no data."""
  dwell = [avg(pools, ('station', s)) or 0 for s in stations]
  travel = []
  for a, b in zip(stations, stations[1:]):
    t = avg(pools, ('segment', frozenset((a, b))))
    if t is None:
      # try folding a skipped station in between (Potomac Yard)
      for via in SKIPPED_STATIONS:
        t1 = avg(pools, ('segment', frozenset((a, via))))
        d = avg(pools, ('station', via))
        t2 = avg(pools, ('segment', frozenset((via, b))))
        if None not in (t1, d, t2):
          t = t1 + d + t2
          break
    travel.append(t or 0)
  return travel, dwell


def emit(f, line, stations, travel, dwell):
  f.write(f'// {line} Line, Track1 order: {stations[0]} -> {stations[-1]}\n')
  f.write(f'static constexpr uint16_t {line}LineTravelS[] = {{\n')
  for i, t in enumerate(travel):
    flag = '' if t else '  // no data: placeholder speed'
    f.write(f'  {t:4d},  // {stations[i]} -> {stations[i + 1]}{flag}\n')
  f.write('};\n')
  f.write(f'static constexpr uint16_t {line}LineDwellS[] = {{\n')
  for s, d in zip(stations, dwell):
    flag = '' if d else '  // no data: fallback dwell setting'
    f.write(f'  {d:4d},  // {s}{flag}\n')
  f.write('};\n')
  f.write(f'static_assert(sizeof({line}LineTravelS) / sizeof({line}LineTravelS[0]) == {line}_Num_LED_Domains,\n'
          f'              "{line}: travel table must have one entry per domain - regenerate with timing/gen_timing.py");\n')
  f.write(f'static_assert(sizeof({line}LineDwellS) / sizeof({line}LineDwellS[0]) == {line}LineNumStationsInLine,\n'
          f'              "{line}: dwell table must have one entry per station - regenerate with timing/gen_timing.py");\n\n')


def main():
  pools = load()
  with open(OUT_PATH, 'w', newline='\n', encoding='utf-8') as f:
    f.write('#pragma once\n')
    f.write('// GENERATED FILE - do not edit by hand.\n')
    f.write('// Source: timing/segment_times.csv (stopwatch rides, see timing/README.md)\n')
    f.write('// Regenerate: python usermods/ASL_v2/timing/gen_timing.py\n')
    f.write('//\n')
    f.write('// Per line, in Track1 order (see asl_map_data.h for track direction notes):\n')
    f.write('//   <Line>LineTravelS[d] = seconds from doors closed at station d to doors\n')
    f.write('//                          open at station d+1 (one entry per domain)\n')
    f.write('//   <Line>LineDwellS[s]  = seconds doors open at station s\n')
    f.write('// 0 = no measurement: the sim uses the "Fallback Station Dwell" setting for\n')
    f.write('// dwell and the legacy 3 s/circuit placeholder speed for travel.\n')
    f.write('// Track2 runs the same timeline in reverse.\n\n')
    f.write('#include "asl_map_data.h"\n\n')
    for line, stations in LINES.items():
      travel, dwell = build(pools, stations)
      emit(f, line, stations, travel, dwell)
      run = sum(travel) + sum(dwell)
      print(f'{line:7s} travel={sum(travel):5d}s dwell={sum(dwell):4d}s measured total={run}s '
            f'({run / 60:.1f} min); missing travel={travel.count(0)} dwell={dwell.count(0)}')
  print(f'wrote {os.path.normpath(OUT_PATH)}')


if __name__ == '__main__':
  main()
# AI: end
