#include "wled.h"
#ifdef ESP32
#include <HTTPClient.h>
#endif
#include "asl_map_data.h"
#include "asl_timing_data.h"   // generated by timing/gen_timing.py

/*
 * ASL_v2 — WMATA metro map usermod (modern self-contained port).
 *
 * Renders the five DC Metro lines on an LED map. Train positions come either
 * from the live WMATA TrainPositions API or from an offline schedule simulator.
 *
 * Architecture:
 *  - The usermod periodically plots a per-line scenery frame (one byte per
 *    LED: track or station) and reconciles the train table into a sprite
 *    list: each train glides from where it is rendered to the fractional LED
 *    of its latest data point over one plot interval, easing in/out of stops.
 *    Circuits flow through the pipeline as floats: the sim interpolates exact
 *    positions from its timetable (continuous motion at any refresh rate),
 *    while live data stays quantized to WMATA's integer circuits.
 *  - Five registered effects ("ASL Red Line" etc.) draw scenery + sprites on
 *    every strip refresh, resolving colors live from the segment's color
 *    slots. Sprites render with two-LED anti-aliasing through a perceptual
 *    (inverse-gamma) weight curve so apparent brightness stays constant
 *    mid-glide. New trains fade in, vanished trains fade out after one cycle
 *    of grace, and implausible jumps (junk/reacquired API data) dissolve
 *    out+in instead of gliding across the map. UI transitions are left to
 *    the WLED core.
 *
 * Setup: create one segment per line sized to that line's LED count, assign
 * the matching ASL effect, and set the three segment colors:
 *   Fx (1st) = train, Bg (2nd) = station, Cs (3rd) = track.
 * Element brightness is part of the picked color (the picker's value slider);
 * segment opacity dims a whole line and global brightness applies on top.
 */

// pixel meaning codes; value doubles as the SEGCOLOR() slot index
#define ASL_PX_TRAIN   0   // color slot only — trains render as moving sprites, not frame pixels
#define ASL_PX_STATION 1
#define ASL_PX_TRACK   2

// line indices into aslLines[]; order matches the effect registration order
#define ASL_LINE_RED    0
#define ASL_LINE_BLUE   1
#define ASL_LINE_GREEN  2
#define ASL_LINE_ORANGE 3
#define ASL_LINE_YELLOW 4

// per-line scenery frames, track + stations only (written by the usermod,
// read by the effects)
static uint8_t RedFrame[Red_Num_LEDS + 1];
static uint8_t BlueFrame[Blue_Num_LEDS + 1];
static uint8_t GreenFrame[Green_Num_LEDS + 1];
static uint8_t OrangeFrame[Orange_Num_LEDS + 1];
static uint8_t YellowFrame[Yellow_Num_LEDS + 1];

// ---- per-line map-data descriptor (indices match ASL_LINE_*) ----
// All per-index tables are in the same geographic order for both tracks
// (index 0 = LED 0); Track1 trains move toward higher indices, Track2 trains
// toward lower ones. See the direction notes in asl_map_data.h.
struct AslLineDef {
  char code[3];                    // WMATA line code
  const uint16_t (*domains[2])[2]; // per-track circuit domains
  const uint16_t *stationSegs[2];  // per-track station circuits
  const uint16_t (*ledArray)[2];   // domain -> LED range (shared by both tracks)
  const uint16_t *stationLEDPos;
  uint16_t numStations;
  uint16_t numDomains;
  const uint16_t *travelS;         // sim: seconds per domain, 0 = not measured (asl_timing_data.h)
  const uint16_t *dwellS;          // sim: seconds per station, 0 = use the fallback dwell setting
};

#define ASL_NUM_LINES 5

static const AslLineDef aslLines[ASL_NUM_LINES] = {
  { "RD", { RedLineTrack1Domains,    RedLineTrack2Domains    }, { RedLineTrack1StationSegments,    RedLineTrack2StationSegments    }, RedLineLEDArray,    RedLineStationLEDPosition,    RedLineNumStationsInLine,    Red_Num_LED_Domains,    RedLineTravelS,    RedLineDwellS    },
  { "BL", { BlueLineTrack1Domains,   BlueLineTrack2Domains   }, { BlueLineTrack1StationSegments,   BlueLineTrack2StationSegments   }, BlueLineLEDArray,   BlueLineStationLEDPosition,   BlueLineNumStationsInLine,   Blue_Num_LED_Domains,   BlueLineTravelS,   BlueLineDwellS   },
  { "GR", { GreenLineTrack1Domains,  GreenLineTrack2Domains  }, { GreenLineTrack1StationSegments,  GreenLineTrack2StationSegments  }, GreenLineLEDArray,  GreenLineStationLEDPosition,  GreenLineNumStationsInLine,  Green_Num_LED_Domains,  GreenLineTravelS,  GreenLineDwellS  },
  { "OR", { OrangeLineTrack1Domains, OrangeLineTrack2Domains }, { OrangeLineTrack1StationSegments, OrangeLineTrack2StationSegments }, OrangeLineLEDArray, OrangeLineStationLEDPosition, OrangeLineNumStationsInLine, Orange_Num_LED_Domains, OrangeLineTravelS, OrangeLineDwellS },
  { "YL", { YellowLineTrack1Domains, YellowLineTrack2Domains }, { YellowLineTrack1StationSegments, YellowLineTrack2StationSegments }, YellowLineLEDArray, YellowLineStationLEDPosition, YellowLineNumStationsInLine, Yellow_Num_LED_Domains, YellowLineTravelS, YellowLineDwellS },
};

// sim timetable sizing: a run has one dwell per station and one travel per
// domain (stations = domains + 1, enforced in asl_map_data.h)
static constexpr size_t aslMaxOf(size_t a, size_t b) { return a > b ? a : b; }
static constexpr size_t ASL_MAX_STATIONS = aslMaxOf(aslMaxOf(aslMaxOf(RedLineNumStationsInLine, BlueLineNumStationsInLine),
                                                             aslMaxOf(GreenLineNumStationsInLine, OrangeLineNumStationsInLine)),
                                                    YellowLineNumStationsInLine);
static constexpr size_t ASL_MAX_PHASES = 2 * ASL_MAX_STATIONS - 1;
// travel speed for a domain with no measured time yet; matches the old
// hand-made timetables (3 s per track circuit)
static constexpr uint32_t ASL_PLACEHOLDER_S_PER_CIRCUIT = 3;

// ---- moving-train sprites ----
// Trains are not baked into the frames; each is a sprite gliding toward the
// fractional LED position of its latest data point, re-targeted every plot
// cycle and rendered with two-LED anti-aliasing at the strip frame rate.
#define ASL_MAX_SPRITES    256   // active trains (<= MAX_TRAINS) + fading ghosts
#define ASL_DEF_FADE_MS    400   // default spawn/despawn fade ("Fade Milliseconds" setting)
#define ASL_TELEPORT_LEDS  8.0f  // moves larger than this dissolve instead of gliding
#define ASL_DEF_AA_GAMMA   2.2f  // default perceptual boost exponent ("Gamma" setting)

// runtime-tunable sprite settings (usermod settings page)
static uint16_t aslFadeMs = ASL_DEF_FADE_MS;  // spawn/despawn fade; also each half of a dissolve
static float    aslGamma  = ASL_DEF_AA_GAMMA; // anti-alias brightness curve, 1.0 = linear

enum : uint8_t { ASL_SPR_FREE = 0, ASL_SPR_LIVE = 1, ASL_SPR_GHOST = 2 };

struct AslSprite {
  uint8_t  mode;         // ASL_SPR_*
  uint8_t  lineIdx;      // ASL_LINE_*
  uint8_t  dir;          // track/direction number, part of the identity key
  uint8_t  missed;       // consecutive plot cycles without a data point
  bool     seen;         // matched during the current reconciliation pass
  uint32_t id;           // train ID (live: WMATA TrainId; sim: departure index + 1)
  float    startPos;     // glide origin (fractional LED)
  float    targetPos;    // glide destination (fractional LED)
  uint32_t moveStartMs;
  uint32_t moveDurMs;    // 0 = parked at targetPos
  uint32_t fadeStartMs;  // spawn (fade-in) or ghost (fade-out) start
};

static AslSprite aslSprites[ASL_MAX_SPRITES];
static uint8_t aslPerceptLUT[256]; // coverage -> blend amount

// perceptual anti-alias curve: boost fractional coverage by 1/gamma so a train
// split across two LEDs reads as bright as one fully lit LED; rebuilt whenever
// the Gamma setting changes
static void aslBuildPerceptLUT() {
  for (int i = 0; i < 256; i++)
    aslPerceptLUT[i] = (uint8_t)(powf((float)i / 255.0f, 1.0f / aslGamma) * 255.0f + 0.5f);
}

// eased (smoothstep) sprite position: accelerates away from a stop, brakes
// into the next one
static float aslSpritePos(const AslSprite& s, uint32_t nowMs) {
  if (s.moveDurMs == 0) return s.targetPos;
  uint32_t el = nowMs - s.moveStartMs;
  if (el >= s.moveDurMs) return s.targetPos;
  float t = (float)el / (float)s.moveDurMs;
  t = t * t * (3.0f - 2.0f * t);
  return s.startPos + (s.targetPos - s.startPos) * t;
}

// current fade alpha (0-255): rises after spawn, falls after ghosting
static uint8_t aslSpriteAlpha(const AslSprite& s, uint32_t nowMs) {
  uint32_t el = nowMs - s.fadeStartMs;
  uint32_t a  = (aslFadeMs == 0 || el >= aslFadeMs) ? 255 : (el * 255) / aslFadeMs;
  return (s.mode == ASL_SPR_GHOST) ? (uint8_t)(255 - a) : (uint8_t)a;
}

// fractional LED for one track's data point: station snap (+/-1 circuit)
// first, then linear interpolation within the containing domain. Circuits are
// float: live data is integer-valued, the sim interpolates between circuits.
// The snap must stay at +/-1 — station circuits sit in the gaps between
// domains, so it is what catches positions there (the sim parks dwelling
// trains exactly on the station circuit, live data reports it directly).
static bool aslTargetForTrack(const AslLineDef& L, uint8_t track, float circuit, float& out) {
  const uint16_t* segs = L.stationSegs[track];
  for (uint16_t x = 0; x < L.numStations; x++) {
    if (fabsf(circuit - (float)segs[x]) <= 1.0f) {
      out = (float)L.stationLEDPos[x];
      return true;
    }
  }
  const uint16_t (*dom)[2] = L.domains[track];
  for (uint16_t y = 0; y < L.numDomains; y++) {
    if (circuit >= dom[y][0] && circuit <= dom[y][1]) {
      uint16_t c0 = dom[y][0], c1 = dom[y][1];
      uint16_t l0 = L.ledArray[y][0], l1 = L.ledArray[y][1];
      out = (c1 > c0) ? (float)l0 + (circuit - (float)c0) * (float)(l1 - l0) / (float)(c1 - c0)
                      : 0.5f * (float)(l0 + l1);
      return true;
    }
  }
  return false;
}

static bool aslTargetLED(uint8_t lineIdx, float circuit, float& out) {
  const AslLineDef& L = aslLines[lineIdx];
  return aslTargetForTrack(L, 0, circuit, out) || aslTargetForTrack(L, 1, circuit, out);
}

static int8_t aslLineIndex(const char* code) {
  for (uint8_t i = 0; i < ASL_NUM_LINES; i++) if (strncmp(code, aslLines[i].code, 2) == 0) return (int8_t)i;
  return -1;
}

static AslSprite* aslFindSprite(uint8_t lineIdx, uint8_t dir, uint32_t id) {
  for (auto &s : aslSprites)
    if (s.mode == ASL_SPR_LIVE && s.lineIdx == lineIdx && s.dir == dir && s.id == id) return &s;
  return nullptr;
}

static void aslSpawnSprite(uint8_t lineIdx, uint8_t dir, uint32_t id, float pos, uint32_t nowMs) {
  for (auto &s : aslSprites) {
    if (s.mode != ASL_SPR_FREE) continue;
    s = { ASL_SPR_LIVE, lineIdx, dir, 0, true, id, pos, pos, nowMs, 0, nowMs };
    return;
  } // table full: the train simply appears on a later cycle
}

static void aslGhostSprite(AslSprite& s, uint32_t nowMs) {
  s.startPos = s.targetPos = aslSpritePos(s, nowMs); // freeze in place while fading out
  s.moveDurMs   = 0;
  s.mode        = ASL_SPR_GHOST;
  s.fadeStartMs = nowMs;
  s.seen        = false;
}

// ---- effects: paint scenery from the frame, then the train sprites on top ----
static void aslDrawFrame(const uint8_t* frame, uint16_t frameLen, uint8_t lineIdx) {
  const int len = SEGLEN;
  for (int i = 0; i < len; i++) {
    uint8_t m = (i < frameLen) ? frame[i] : ASL_PX_TRACK;
    SEGMENT.setPixelColor(i, SEGCOLOR(m));
  }

  const uint32_t trainC = SEGCOLOR(ASL_PX_TRAIN);
  const uint32_t nowMs  = millis();
  for (unsigned n = 0; n < ASL_MAX_SPRITES; n++) {
    const AslSprite& s = aslSprites[n];
    if (s.mode == ASL_SPR_FREE || s.lineIdx != lineIdx) continue;
    uint8_t alpha = aslSpriteAlpha(s, nowMs);
    if (alpha == 0) continue;
    float pos  = aslSpritePos(s, nowMs);
    int   i0   = (int)floorf(pos);
    float frac = pos - (float)i0;
    // split coverage * fade alpha across the two straddled LEDs, boosted
    // through the perceptual LUT so apparent brightness holds mid-glide
    unsigned w0 = (unsigned)((1.0f - frac) * alpha + 0.5f);
    unsigned w1 = (unsigned)(frac * alpha + 0.5f);
    if (w0 > 0 && i0 >= 0 && i0 < len)
      SEGMENT.setPixelColor(i0, color_blend(SEGMENT.getPixelColor(i0), trainC, aslPerceptLUT[w0 > 255 ? 255 : w0]));
    if (w1 > 0 && i0 + 1 >= 0 && i0 + 1 < len)
      SEGMENT.setPixelColor(i0 + 1, color_blend(SEGMENT.getPixelColor(i0 + 1), trainC, aslPerceptLUT[w1 > 255 ? 255 : w1]));
  }
}

static void mode_asl_red(void)    { aslDrawFrame(RedFrame,    sizeof(RedFrame),    ASL_LINE_RED);    }
static void mode_asl_blue(void)   { aslDrawFrame(BlueFrame,   sizeof(BlueFrame),   ASL_LINE_BLUE);   }
static void mode_asl_green(void)  { aslDrawFrame(GreenFrame,  sizeof(GreenFrame),  ASL_LINE_GREEN);  }
static void mode_asl_orange(void) { aslDrawFrame(OrangeFrame, sizeof(OrangeFrame), ASL_LINE_ORANGE); }
static void mode_asl_yellow(void) { aslDrawFrame(YellowFrame, sizeof(YellowFrame), ASL_LINE_YELLOW); }

static const char _data_FX_ASL_RED[]    PROGMEM = "ASL Red Line@;Train,Station,Track;;1";
static const char _data_FX_ASL_BLUE[]   PROGMEM = "ASL Blue Line@;Train,Station,Track;;1";
static const char _data_FX_ASL_GREEN[]  PROGMEM = "ASL Green Line@;Train,Station,Track;;1";
static const char _data_FX_ASL_ORANGE[] PROGMEM = "ASL Orange Line@;Train,Station,Track;;1";
static const char _data_FX_ASL_YELLOW[] PROGMEM = "ASL Yellow Line@;Train,Station,Track;;1";


class UsermodASL : public Usermod {
  private:
    static const uint16_t MAX_TRAINS = 256; // all 10 tracks at rush headway fit comfortably

    // factory defaults — single source of truth: they initialize the members
    // below, back every readFromConfig fallback, and thus pre-populate the
    // settings boxes on a device with no saved config
    // WMATA weekday hours: open 05:00, close midnight (00:00 wraps via the
    // modulo schedule math; Fri/Sat really close at 02:00 but the sim has one schedule)
    static const uint32_t DEF_OPEN_S     = 18000;  // 05:00
    static const uint32_t DEF_CLOSE_S    = 0;      // 00:00 = midnight
    static const uint32_t DEF_HEADWAY_S  = 360;    // 6 min
    static const uint32_t DEF_DWELL_S    = 25;     // fallback dwell; measured dwells are 15-45 s
    static const uint32_t MAX_DWELL_S    = 600;
    static const uint32_t DEF_REFRESH_MS = 5000;
    // rush defaults per WMATA's published FY2026 peak service (7-9am, 4-6pm,
    // Red line "at least every four minutes")
    static const uint32_t DEF_AM_RUSH_START_S = 25200; // 07:00
    static const uint32_t DEF_AM_RUSH_END_S   = 32400; // 09:00
    static const uint32_t DEF_PM_RUSH_START_S = 57600; // 16:00
    static const uint32_t DEF_PM_RUSH_END_S   = 64800; // 18:00
    static const uint32_t DEF_RUSH_HEADWAY_S  = 240;   // 4 min

    bool enabled = true;
    bool initDone = false;
    unsigned long lastTime = 0;

    // ---- config (usermod settings page) ----
    // times are stored internally as seconds; in cfg.json open/close are "HH:MM"
    // strings and headway is minutes (decimals ok), converted in read/addToConfig
    bool     simModeEnable = true;
    String   serverAddress = "http://api.wmata.com/TrainPositions/TrainPositions?contentType=json";
    String   apiKey = "";
    uint32_t systemFirstTrainTime = DEF_OPEN_S;    // second of day the first train departs
    uint32_t systemLastTrainTime  = DEF_CLOSE_S;   // second of day the last train departs
    uint32_t headwayTimeSeconds   = DEF_HEADWAY_S; // seconds between train departures
    uint32_t amRushStartTime = DEF_AM_RUSH_START_S; // rush windows: same-day seconds; start >= end disables the window
    uint32_t amRushEndTime   = DEF_AM_RUSH_END_S;
    uint32_t pmRushStartTime = DEF_PM_RUSH_START_S;
    uint32_t pmRushEndTime   = DEF_PM_RUSH_END_S;
    uint32_t rushHeadwayTimeSeconds = DEF_RUSH_HEADWAY_S; // 0 = no rush service
    uint32_t stationDwellTimeS    = DEF_DWELL_S;   // sim: dwell at stations without a measured value (terminals, data gaps)
    uint32_t plotRefreshIntervalMs = DEF_REFRESH_MS; // data refresh; below ~3.5s angers WMATA servers

    // ---- runtime state ----
    uint32_t secondOfDay = 0;               // the sim's time of day: real local time + simOffsetS
    uint32_t simOffsetS  = 0;               // sim test offset (0..86399 s); runtime only, never saved,
                                            // never touches the real clock or the RTC chip
    bool     delaysRacked = false;          // sim timetables built for the current settings?
    uint32_t phaseEndS[ASL_NUM_LINES][ASL_MAX_PHASES]; // per line: cumulative end time of each dwell/travel phase (Track1 order)
    uint32_t runS[ASL_NUM_LINES];                      // per line: end-to-end run time in seconds

    // train table (compact; one entry per active train this cycle)
    uint16_t numTrains = 0;
    uint32_t trainId[MAX_TRAINS];
    float    trainCircuit[MAX_TRAINS]; // fractional: sim interpolates between circuits, live is integer-valued
    uint8_t  trainDirection[MAX_TRAINS];
    uint8_t  trainCars[MAX_TRAINS];
    uint8_t  trainSecondsAtLoc[MAX_TRAINS];
    char     trainLine[MAX_TRAINS][3];
    bool     trainNormal[MAX_TRAINS];

    static const char _name[];
    static const char _enabled[];

    // "HH:MM" -> second of day; returns fallback on malformed/out-of-range input
    static uint32_t parseHHMM(const char* s, uint32_t fallback) {
      int h = -1, m = -1;
      if (!s || sscanf(s, "%d:%d", &h, &m) != 2) return fallback;
      if (h < 0 || h > 23 || m < 0 || m > 59) return fallback;
      return h * 3600UL + m * 60UL;
    }

    // real local time of day from WLED's clock (NTP, RTC or browser-set)
    static uint32_t realSecondOfDay() {
      return hour(localTime) * 3600UL + minute(localTime) * 60UL + second(localTime);
    }

    // AI: below section was generated by an AI
    // Human-readable name for WLED's current time source. Toki ranks sources
    // by accuracy (wled00/src/dependencies/toki/Toki.h); the RTC usermod sets
    // TOKI_TS_RTC at boot, the web UI and "Set clock from this device" set
    // TOKI_TS_JSON, NTP sets TOKI_TS_NTP.
    static const __FlashStringHelper* timeSourceName(uint8_t src) {
      if (src == TOKI_TS_NONE)    return F("not set");
      if (src >= TOKI_TS_NTP)     return F("NTP");
      if (src >= TOKI_TS_UDP_NTP) return F("network sync");
      if (src >= TOKI_TS_JSON)    return F("browser / API");
      if (src >= TOKI_TS_RTC)     return F("RTC");
      return F("low-accuracy sync");
    }
    // AI: end

    static void formatHHMM(uint32_t secOfDay, char* buf, size_t len) {
      snprintf(buf, len, "%02u:%02u", (unsigned)(secOfDay / 3600UL) % 24, (unsigned)((secOfDay / 60UL) % 60));
    }

    void clearTrains() { numTrains = 0; }

    void injectSimTrain(uint16_t simIdx, uint8_t dir, float circuit, const char* lineCode) {
      if (numTrains >= MAX_TRAINS) return;
      uint16_t i = numTrains++;
      trainId[i]           = simIdx + 1;
      trainCircuit[i]      = circuit;
      trainDirection[i]    = dir;
      trainCars[i]         = 8;
      trainSecondsAtLoc[i] = 2;
      strlcpy(trainLine[i], lineCode, sizeof(trainLine[i]));
      trainNormal[i]       = true;
    }

    // headway in effect for a departure at this second of day: rush windows
    // shorten it; a window with start >= end is disabled, rush headway 0
    // disables rush entirely
    uint32_t headwayAt(uint32_t sod) const {
      if (rushHeadwayTimeSeconds == 0) return headwayTimeSeconds;
      if ((amRushStartTime < amRushEndTime && sod >= amRushStartTime && sod < amRushEndTime) ||
          (pmRushStartTime < pmRushEndTime && sod >= pmRushStartTime && sod < pmRushEndTime))
        return rushHeadwayTimeSeconds;
      return headwayTimeSeconds;
    }

    // AI: below section was generated by an AI
    // Build each line's Track1 timeline from the measured timing tables
    // (asl_timing_data.h) and the fallback dwell setting. A run alternates
    // dwell at station 0, travel over domain 0, dwell at station 1, ... dwell
    // at the last station; phaseEndS[line][p] holds the cumulative end time of
    // phase p, so even p = dwell at station p/2, odd p = travel over domain p/2.
    // Track2 needs no table of its own: it is the same timeline run backwards.
    // Called again whenever settings are saved (delaysRacked is cleared in
    // readFromConfig), so a new fallback dwell applies without a reboot.
    void rackTimetables() {
      for (uint8_t li = 0; li < ASL_NUM_LINES; li++) {
        const AslLineDef& L = aslLines[li];
        uint32_t acc = 0;
        for (uint16_t k = 0; k < L.numStations; k++) {
          acc += L.dwellS[k] ? L.dwellS[k] : stationDwellTimeS; // 0 = not measured (terminals, gaps)
          phaseEndS[li][2 * k] = acc;
          if (k < L.numDomains) {
            uint32_t travel = L.travelS[k];
            if (travel == 0) {
              // not measured yet: keep the old hand-made tables' speed so the
              // gap neither freezes trains nor teleports them
              const uint16_t* d = L.domains[0][k];
              uint32_t circuits = ((d[1] >= d[0]) ? d[1] - d[0] : d[0] - d[1]) + 1;
              travel = circuits * ASL_PLACEHOLDER_S_PER_CIRCUIT;
            }
            acc += travel;
            phaseEndS[li][2 * k + 1] = acc;
          }
        }
        runS[li] = acc;
        DEBUG_PRINTF_P(PSTR("ASL: %s run %u s\n"), L.code, (unsigned)acc);
      }
      delaysRacked = true;
    }

    // Simulate all trains currently en route on one track (0 = Track1,
    // 1 = Track2) of one line. Trains depart from open to close, each gap set
    // by the headway in effect at the departure it follows (rush windows
    // shorten it). A train's position comes from the phase of the timetable
    // that brackets "now - departure": dwelling trains sit on their station
    // circuit, moving trains are interpolated across the domain's circuits.
    // All schedule math is modulo 24h, so service may span midnight (close
    // before open, open == close = 24h) and late runs keep going past the
    // date line.
    void offlineSimTrains(uint8_t li, uint8_t track) {
      const AslLineDef& L = aslLines[li];
      const uint32_t runDuration = runS[li]; // end-to-end run time, both tracks
      if (runDuration == 0 || headwayTimeSeconds == 0) return;
      const uint16_t lastPhase = 2 * L.numStations - 2;
      uint32_t opDuration = (systemLastTrainTime > systemFirstTrainTime)
                          ? systemLastTrainTime - systemFirstTrainTime
                          : 86400UL - systemFirstTrainTime + systemLastTrainTime;

      // a departure exactly at close is the last train, except in 24h service
      // where elapsed == 86400 is the first departure again (duplicate train)
      uint32_t lastElapsed = (opDuration >= 86400UL) ? opDuration - 1 : opDuration;

      uint32_t elapsed = 0; // seconds from open to this departure
      for (uint32_t i = 0; elapsed <= lastElapsed && i < 4096; i++) {
        uint32_t departure = (systemFirstTrainTime + elapsed) % 86400UL;
        elapsed += headwayAt(departure);
        uint32_t t = (secondOfDay + 86400UL - departure) % 86400UL; // seconds into this train's run, wrap-safe
        if (t == 0 || t >= runDuration) continue;

        // Track1 runs the timeline forward from station 0; Track2 starts at
        // the far end, so its position at time t is Track1's at runDuration - t
        uint32_t s = (track == 0) ? t : runDuration - t;
        uint16_t p = 0;
        while (p < lastPhase && s > phaseEndS[li][p]) p++;
        uint32_t p0  = p ? phaseEndS[li][p - 1] : 0;
        uint32_t len = phaseEndS[li][p] - p0;

        float circuit;
        if ((p & 1) == 0) {
          // dwelling: park on the station circuit; the renderer's +/-1 station
          // snap puts it on the station LED
          circuit = (float)L.stationSegs[track][p / 2];
        } else {
          // moving: fraction of the domain covered, measured in the Track1
          // (LED-ascending) sense, which is how {first,last} map to LEDs on
          // both tracks. For Track2 the mirrored time makes it run downward.
          float frac = len ? (float)(s - p0) / (float)len : 0.0f;
          const uint16_t* d = L.domains[track][p / 2];
          circuit = (float)d[0] + frac * ((float)d[1] - (float)d[0]);
        }
        injectSimTrain(i, track + 1, circuit, L.code);
      }
    }
    // AI: end

    // fetch live train positions from the WMATA API into the train table
    void getWMATAData() {
#ifdef ESP32
      if (apiKey.length() == 0) return;
      HTTPClient http;
      http.setConnectTimeout(3000);
      http.setTimeout(5000);
      String url = serverAddress + "&api_key=" + apiKey;
      if (!http.begin(url)) return;
      int code = http.GET();
      if (code != HTTP_CODE_OK) {
        DEBUG_PRINTF_P(PSTR("ASL: WMATA HTTP error %d\n"), code);
        http.end();
        return;
      }
      String payload = http.getString();
      http.end();

      DynamicJsonDocument doc(24576);
      DeserializationError err = deserializeJson(doc, payload);
      if (err) {
        DEBUG_PRINTF_P(PSTR("ASL: JSON parse failed: %s\n"), err.c_str());
        return;
      }
      JsonArray positions = doc["TrainPositions"];
      uint16_t n = positions.size();
      if (n > MAX_TRAINS) n = MAX_TRAINS;
      for (uint16_t i = 0; i < n; i++) {
        JsonObject t = positions[i];
        trainId[i]           = t["TrainId"] | 0UL;
        trainCircuit[i]      = (float)(t["CircuitId"] | 0UL);
        trainDirection[i]    = t["DirectionNum"] | 0;
        trainCars[i]         = t["CarCount"] | 0;
        trainSecondsAtLoc[i] = t["SecondsAtLocation"] | 0;
        strlcpy(trainLine[i], t["LineCode"] | "", sizeof(trainLine[i]));
        trainNormal[i]       = (strcmp(t["ServiceType"] | "", "Normal") == 0);
      }
      numTrains = n;
      DEBUG_PRINTF_P(PSTR("ASL: fetched %u trains\n"), numTrains);
#endif
    }

    void clearFrame(uint8_t frame[], uint16_t frameLen) {
      memset(frame, ASL_PX_TRACK, frameLen);
    }

    void plotStations(uint8_t frame[], uint16_t frameLen, const uint16_t stationLEDPos[], uint16_t numStations) {
      for (uint16_t i = 0; i < numStations; i++) {
        if (stationLEDPos[i] < frameLen) frame[stationLEDPos[i]] = ASL_PX_STATION;
      }
    }

    // reconcile the train table into the sprite list: matched trains re-target
    // (gliding there over one plot interval), new trains fade in, vanished
    // trains get one cycle of grace then fade out, and implausible jumps
    // dissolve out+in instead of gliding (junk/reacquired API data)
    void updateTrainSprites(uint32_t nowMs) {
      for (auto &s : aslSprites) {
        if (s.mode == ASL_SPR_GHOST && nowMs - s.fadeStartMs >= aslFadeMs) s.mode = ASL_SPR_FREE;
        s.seen = false;
      }
      for (uint16_t i = 0; i < numTrains; i++) {
        if (!trainNormal[i]) continue;
        int8_t li = aslLineIndex(trainLine[i]);
        if (li < 0) continue;
        float target;
        if (!aslTargetLED(li, trainCircuit[i], target)) continue; // circuit outside the mapped domains
        AslSprite* s = aslFindSprite(li, trainDirection[i], trainId[i]);
        if (!s) {
          aslSpawnSprite(li, trainDirection[i], trainId[i], target, nowMs);
          continue;
        }
        s->seen = true;
        s->missed = 0;
        float cur = aslSpritePos(*s, nowMs);
        if (fabsf(target - cur) <= ASL_TELEPORT_LEDS) {
          s->startPos    = cur;
          s->targetPos   = target;
          s->moveStartMs = nowMs;
          s->moveDurMs   = plotRefreshIntervalMs;
        } else {
          aslGhostSprite(*s, nowMs);
          aslSpawnSprite(li, trainDirection[i], trainId[i], target, nowMs);
        }
      }
      for (auto &s : aslSprites) {
        if (s.mode == ASL_SPR_LIVE && !s.seen && ++s.missed > 1) aslGhostSprite(s, nowMs);
      }
    }

    void plotScenery() {
      clearFrame(RedFrame, sizeof(RedFrame));
      plotStations(RedFrame, sizeof(RedFrame), RedLineStationLEDPosition, RedLineNumStationsInLine);
      clearFrame(BlueFrame, sizeof(BlueFrame));
      plotStations(BlueFrame, sizeof(BlueFrame), BlueLineStationLEDPosition, BlueLineNumStationsInLine);
      clearFrame(GreenFrame, sizeof(GreenFrame));
      plotStations(GreenFrame, sizeof(GreenFrame), GreenLineStationLEDPosition, GreenLineNumStationsInLine);
      clearFrame(OrangeFrame, sizeof(OrangeFrame));
      plotStations(OrangeFrame, sizeof(OrangeFrame), OrangeLineStationLEDPosition, OrangeLineNumStationsInLine);
      clearFrame(YellowFrame, sizeof(YellowFrame));
      plotStations(YellowFrame, sizeof(YellowFrame), YellowLineStationLEDPosition, YellowLineNumStationsInLine);
    }

  public:
    void setup() override {
      aslBuildPerceptLUT(); // usually already built by readFromConfig; harmless to redo
      strip.addEffect(255, &mode_asl_red,    _data_FX_ASL_RED);
      strip.addEffect(255, &mode_asl_blue,   _data_FX_ASL_BLUE);
      strip.addEffect(255, &mode_asl_green,  _data_FX_ASL_GREEN);
      strip.addEffect(255, &mode_asl_orange, _data_FX_ASL_ORANGE);
      strip.addEffect(255, &mode_asl_yellow, _data_FX_ASL_YELLOW);
      initDone = true;
    }

    void loop() override {
      if (!enabled || (strip.isUpdating() && (millis() - lastTime < plotRefreshIntervalMs + 200))) return;
      if (millis() - lastTime < plotRefreshIntervalMs) return;
      lastTime = millis();

      secondOfDay = (realSecondOfDay() + simOffsetS) % 86400UL; // sim clock; offset is 0 unless a test time is set

      if (!delaysRacked) rackTimetables();
      clearTrains();
      if (simModeEnable) {
        for (uint8_t li = 0; li < ASL_NUM_LINES; li++) {
          offlineSimTrains(li, 0); // Track1
          offlineSimTrains(li, 1); // Track2
        }
      } else if (WLED_CONNECTED) {
        getWMATAData();
      }
      plotScenery();
      updateTrainSprites(millis());
    }

    void addToJsonInfo(JsonObject& root) override {
      JsonObject user = root["u"];
      if (user.isNull()) user = root.createNestedObject("u");
      JsonArray arr = user.createNestedArray(F("ASL trains"));
      arr.add(numTrains);
      arr.add(simModeEnable ? F(" (sim)") : F(" (live)"));

      // AI: below section was generated by an AI
      // clock status: the sim is only as right as WLED's clock, which offline
      // comes from the RTC usermod (or "Set clock from this device")
      char buf[24];
      uint8_t src = toki.getTimeSource();
      JsonArray clk = user.createNestedArray(F("ASL clock"));
      if (src == TOKI_TS_NONE) {
        clk.add(F("not set"));
        clk.add(simModeEnable ? F(" - sim schedule is wrong (needs NTP, RTC or Set clock)") : F(""));
      } else {
        uint32_t sod = realSecondOfDay();
        snprintf(buf, sizeof(buf), "%02u:%02u:%02u", (unsigned)(sod / 3600), (unsigned)(sod / 60 % 60), (unsigned)(sod % 60));
        clk.add(buf);
        String from = F(" (");
        from += timeSourceName(src);
        from += ')';
        clk.add(from);
      }
      if (simOffsetS) {
        JsonArray st = user.createNestedArray(F("ASL sim time"));
        formatHHMM((realSecondOfDay() + simOffsetS) % 86400UL, buf, sizeof(buf));
        st.add(buf);
        st.add(F(" (test time, cleared on reboot)"));
      }
      // AI: end
    }

    // AI: below section was generated by an AI
    // Sim test time, set from the buttons on the usermod settings page (or any
    // JSON client):
    //   {"ASL":{"simAt":"14:30"}}   run the sim as if it were 14:30 now
    //   {"ASL":{"simReset":true}}   back to real time
    // Stored as an offset from the real clock so the sim keeps ticking from the
    // chosen time. Runtime only: not written to cfg.json, cleared by a reboot,
    // and the real clock / RTC chip are never changed.
    void readFromJsonState(JsonObject& root) override {
      JsonObject um = root[F("ASL")];
      if (um.isNull()) return;
      if (um[F("simReset")] | false) simOffsetS = 0;
      const char* at = um[F("simAt")] | (const char*)nullptr;
      if (at) {
        uint32_t target = parseHHMM(at, UINT32_MAX);
        if (target != UINT32_MAX) simOffsetS = (target + 86400UL - realSecondOfDay()) % 86400UL;
      }
      lastTime = 0; // replot on the next loop instead of waiting a refresh interval
    }
    // AI: end

    void addToConfig(JsonObject& root) override {
      JsonObject top = root.createNestedObject(FPSTR(_name));
      top[FPSTR(_enabled)]                = enabled;
      top[F("Enable Train Sim Mode")]     = simModeEnable;
      top[F("Server Address")]            = serverAddress;
      top[F("API Key")]                   = apiKey;
      char hhmm[6];
      formatHHMM(systemFirstTrainTime, hhmm, sizeof(hhmm));
      top[F("System Open Time")]          = hhmm;
      formatHHMM(systemLastTrainTime, hhmm, sizeof(hhmm));
      top[F("System Close Time")]         = hhmm;
      top[F("Train Headway")]             = headwayTimeSeconds / 60.0f;
      formatHHMM(amRushStartTime, hhmm, sizeof(hhmm));
      top[F("Morning Rush Hour Start")]   = hhmm;
      formatHHMM(amRushEndTime, hhmm, sizeof(hhmm));
      top[F("Morning Rush Hour End")]     = hhmm;
      formatHHMM(pmRushStartTime, hhmm, sizeof(hhmm));
      top[F("Evening Rush Hour Start")]   = hhmm;
      formatHHMM(pmRushEndTime, hhmm, sizeof(hhmm));
      top[F("Evening Rush Hour End")]     = hhmm;
      top[F("Rush Hour Train Headway")]   = rushHeadwayTimeSeconds / 60.0f;
      top[F("Fallback Station Dwell (s)")] = stationDwellTimeS;
      top[F("Plot Refresh Interval (ms)")] = plotRefreshIntervalMs;
      top[F("Fade Milliseconds")]         = aslFadeMs;
      top[F("Gamma")]                     = aslGamma;
    }

    bool readFromConfig(JsonObject& root) override {
      JsonObject top = root[FPSTR(_name)];
      bool configComplete = !top.isNull();

      configComplete &= getJsonValue(top[FPSTR(_enabled)], enabled, true);
      configComplete &= getJsonValue(top[F("Enable Train Sim Mode")], simModeEnable, true);
      configComplete &= getJsonValue(top[F("Server Address")], serverAddress);
      configComplete &= getJsonValue(top[F("API Key")], apiKey);

      String hhmm;
      configComplete &= getJsonValue(top[F("System Open Time")], hhmm, "");
      systemFirstTrainTime = parseHHMM(hhmm.c_str(), DEF_OPEN_S);
      configComplete &= getJsonValue(top[F("System Close Time")], hhmm, "");
      systemLastTrainTime  = parseHHMM(hhmm.c_str(), DEF_CLOSE_S);

      float headwayMin = 0.0f;
      configComplete &= getJsonValue(top[F("Train Headway")], headwayMin, 0.0f);
      headwayTimeSeconds = (headwayMin > 0.0f) ? (uint32_t)(headwayMin * 60.0f + 0.5f) : 0;
      if (headwayTimeSeconds == 0) headwayTimeSeconds = DEF_HEADWAY_S; // missing, non-positive, or rounds to zero

      configComplete &= getJsonValue(top[F("Morning Rush Hour Start")], hhmm, "");
      amRushStartTime = parseHHMM(hhmm.c_str(), DEF_AM_RUSH_START_S);
      configComplete &= getJsonValue(top[F("Morning Rush Hour End")], hhmm, "");
      amRushEndTime   = parseHHMM(hhmm.c_str(), DEF_AM_RUSH_END_S);
      configComplete &= getJsonValue(top[F("Evening Rush Hour Start")], hhmm, "");
      pmRushStartTime = parseHHMM(hhmm.c_str(), DEF_PM_RUSH_START_S);
      configComplete &= getJsonValue(top[F("Evening Rush Hour End")], hhmm, "");
      pmRushEndTime   = parseHHMM(hhmm.c_str(), DEF_PM_RUSH_END_S);

      // 0 (or negative) rush headway = rush disabled; missing = default 4 min
      float rushMin = 0.0f;
      configComplete &= getJsonValue(top[F("Rush Hour Train Headway")], rushMin, DEF_RUSH_HEADWAY_S / 60.0f);
      rushHeadwayTimeSeconds = (rushMin > 0.0f) ? (uint32_t)(rushMin * 60.0f + 0.5f) : 0;

      // any open/close combination is valid: close before open wraps past
      // midnight, open == close means 24-hour service

      // whole seconds; used only where no dwell was measured (terminals, data
      // gaps). An empty field arrives as 0, so 0 also means "use the default".
      configComplete &= getJsonValue(top[F("Fallback Station Dwell (s)")], stationDwellTimeS, DEF_DWELL_S);
      if (stationDwellTimeS == 0) stationDwellTimeS = DEF_DWELL_S;
      if (stationDwellTimeS > MAX_DWELL_S) stationDwellTimeS = MAX_DWELL_S;
      configComplete &= getJsonValue(top[F("Plot Refresh Interval (ms)")], plotRefreshIntervalMs, DEF_REFRESH_MS);
      if (plotRefreshIntervalMs < 1000) plotRefreshIntervalMs = 1000;

      configComplete &= getJsonValue(top[F("Fade Milliseconds")], aslFadeMs, (uint16_t)ASL_DEF_FADE_MS);
      if (aslFadeMs > 5000) aslFadeMs = 5000;
      configComplete &= getJsonValue(top[F("Gamma")], aslGamma, ASL_DEF_AA_GAMMA);
      if (aslGamma < 1.0f) aslGamma = 1.0f;
      if (aslGamma > 4.0f) aslGamma = 4.0f;
      aslBuildPerceptLUT(); // gamma may have changed

      delaysRacked = false; // timing settings may have changed; re-rack on next loop
      return configComplete;
    }

    void appendConfigData(Print& settingsScript) override {
      // upgrade the open/close text fields to native HH:MM time pickers;
      // [0] of each named pair is the hidden type field, [1] the visible input
      settingsScript.printf_P(PSTR(
        "for(let n of['System Open Time','System Close Time',"
          "'Morning Rush Hour Start','Morning Rush Hour End',"
          "'Evening Rush Hour Start','Evening Rush Hour End']){"
          "let f=d.getElementsByName('%s:'+n);"
          "if(f[1]){f[1].type='time';f[1].style.width='120px';}}"), _name);
      settingsScript.printf_P(PSTR("addInfo('%s:System Close Time',1,'earlier than open = service past midnight; equal = 24h');"), _name);
      settingsScript.printf_P(PSTR("addInfo('%s:Train Headway',1,'minutes between departures (decimals ok)');"), _name);
      settingsScript.printf_P(PSTR("addInfo('%s:Morning Rush Hour End',1,'rush windows are same-day; start at/after end disables one');"), _name);
      settingsScript.printf_P(PSTR("addInfo('%s:Rush Hour Train Headway',1,'minutes between departures in rush windows (0 = no rush service)');"), _name);
      settingsScript.printf_P(PSTR("addInfo('%s:Fallback Station Dwell (s)',1,'whole seconds; sim dwell at terminals and stations with no measured time (blank = 25)');"), _name);
      settingsScript.printf_P(PSTR("addInfo('%s:API Key',1,'WMATA key, only used in live mode');"), _name);
      settingsScript.printf_P(PSTR("addInfo('%s:Fade Milliseconds',1,'train appear/vanish fade (0 = instant, max 5000)');"), _name);
      settingsScript.printf_P(PSTR("addInfo('%s:Gamma',1,'motion anti-alias brightness curve, 1 = linear');"), _name);

      // AI: below section was generated by an AI
      // Clock block under "Enable Train Sim Mode": live clock status (read
      // from this usermod's /json/info rows), a button that sets WLED's clock
      // from the browser (same {"time":...} the main UI sends; the RTC usermod
      // then writes it to the chip), and the temporary sim test time
      // (readFromJsonState). This script runs inside the page's GetV()
      // function, so the button handlers are attached to window.
      settingsScript.printf_P(PSTR(
        "{"
        "window.aslU=()=>fetch(getURL('/json/info')).then(r=>r.json()).then(j=>{"
          "let u=j.u||{},c=u['ASL clock'],s=u['ASL sim time'];"
          "gId('aslS').innerHTML='<b>Clock:</b> '+esc(c?c.join(''):'?')+(s?'<br><b>Sim time:</b> '+esc(s.join('')):'');"
        "}).catch(()=>{});"
        "window.aslP=o=>fetch(getURL('/json/state'),{method:'POST',headers:{'Content-Type':'application/json'},"
          "body:JSON.stringify(o)}).then(()=>setTimeout(aslU,500)).catch(()=>{});"
        "window.aslClock=()=>aslP({time:Math.floor(Date.now()/1000)});"
        "window.aslApply=()=>{let v=gId('aslTm').value;if(v)aslP({ASL:{simAt:v}});};"
        "window.aslReal=()=>aslP({ASL:{simReset:true}});"
        "let f=d.getElementsByName('%s:Enable Train Sim Mode');"
        "if(f.length)f[f.length-1].insertAdjacentHTML('afterend',"
          "'<div style=\"margin:6px 0 10px\"><div id=\"aslS\">Clock: ...</div>"
          "<button type=\"button\" onclick=\"aslClock()\">Set clock from this device</button><br>"
          "Sim test time <input type=\"time\" id=\"aslTm\" style=\"width:120px\"> "
          "<button type=\"button\" onclick=\"aslApply()\">Apply</button> "
          "<button type=\"button\" onclick=\"aslReal()\">Real time</button><br>"
          "<i>Test time changes the sim only: not saved, cleared on reboot, real clock and RTC untouched.</i></div>');"
        "aslU();"
        "}"), _name);
      // AI: end
    }

    uint16_t getId() override { return USERMOD_ID_UNSPECIFIED; }
};

const char UsermodASL::_name[]    PROGMEM = "ASL-usermod-v2";
const char UsermodASL::_enabled[] PROGMEM = "enabled";

static UsermodASL asl_usermod;
REGISTER_USERMOD(asl_usermod);
