#include "wled.h"
#ifdef ESP32
#include <HTTPClient.h>
#endif
#include "asl_map_data.h"
#include "asl_timing_data.h"   // generated by timing/gen_timing.py
#include "src/dependencies/time/DS1307RTC.h" // RTC.chipPresent() for the Info panel (flag only, no I2C traffic)

/*
 * ASL_v2 — WMATA metro map usermod (modern self-contained port).
 *
 * Renders the five DC Metro lines on an LED map. Train positions come either
 * from the live WMATA TrainPositions API or from an offline schedule simulator.
 *
 * Architecture:
 *  - The usermod periodically plots a per-line scenery frame (one byte per
 *    LED: track or station) and reconciles the train table into a sprite
 *    list: each train glides from where it is rendered to the fractional LED
 *    of its latest data point at constant speed, timed to arrive when the
 *    next data point is due (live: the measured WMATA refresh interval).
 *    Circuits flow through the pipeline as floats: the sim interpolates exact
 *    positions from its timetable (continuous motion at any refresh rate),
 *    while live data stays quantized to WMATA's integer circuits.
 *  - Five registered effects ("ASL Red Line" etc.) draw scenery + sprites on
 *    every strip refresh, resolving colors live from the segment's color
 *    slots. A sprite sits on one LED and crossfades to the next only inside a
 *    short window around the midpoint ("Train Crossfade"), weighted through a
 *    perceptual (inverse-gamma) curve so apparent brightness holds during the
 *    handover. New trains fade in, vanished trains fade out (live data after
 *    one cycle of grace), and implausible jumps (junk/reacquired API data) dissolve
 *    out+in instead of gliding across the map. UI transitions are left to
 *    the WLED core.
 *
 * Setup: create one segment per line sized to that line's LED count, assign
 * the matching ASL effect, and set the three segment colors:
 *   Fx (1st) = train, Bg (2nd) = station, Cs (3rd) = track.
 * Element brightness is part of the picked color (the picker's value slider);
 * segment opacity dims a whole line and global brightness applies on top.
 */

// pixel meaning codes; value doubles as the SEGCOLOR() slot index
#define ASL_PX_TRAIN   0   // color slot only — trains render as moving sprites, not frame pixels
#define ASL_PX_STATION 1
#define ASL_PX_TRACK   2

// line indices into aslLines[]; order matches the effect registration order
#define ASL_LINE_RED    0
#define ASL_LINE_BLUE   1
#define ASL_LINE_GREEN  2
#define ASL_LINE_ORANGE 3
#define ASL_LINE_YELLOW 4

// per-line scenery frames, track + stations only (written by the usermod,
// read by the effects)
static uint8_t RedFrame[Red_Num_LEDS + 1];
static uint8_t BlueFrame[Blue_Num_LEDS + 1];
static uint8_t GreenFrame[Green_Num_LEDS + 1];
static uint8_t OrangeFrame[Orange_Num_LEDS + 1];
static uint8_t YellowFrame[Yellow_Num_LEDS + 1];

// ---- per-line map-data descriptor (indices match ASL_LINE_*) ----
// All per-index tables are in the same geographic order for both tracks
// (index 0 = LED 0); Track1 trains move toward higher indices, Track2 trains
// toward lower ones. See the direction notes in asl_map_data.h.
struct AslLineDef {
  char code[3];                    // WMATA line code
  const uint16_t (*domains[2])[2]; // per-track circuit domains
  const uint16_t *stationSegs[2];  // per-track station circuits
  const uint16_t (*ledArray)[2];   // domain -> LED range (shared by both tracks)
  const uint16_t *stationLEDPos;
  uint16_t numStations;
  uint16_t numDomains;
  const uint16_t *travelS;         // sim: seconds per domain, 0 = not measured (asl_timing_data.h)
  const uint16_t *dwellS;          // sim: seconds per station, 0 = use the fallback dwell setting
};

#define ASL_NUM_LINES 5

static const AslLineDef aslLines[ASL_NUM_LINES] = {
  { "RD", { RedLineTrack1Domains,    RedLineTrack2Domains    }, { RedLineTrack1StationSegments,    RedLineTrack2StationSegments    }, RedLineLEDArray,    RedLineStationLEDPosition,    RedLineNumStationsInLine,    Red_Num_LED_Domains,    RedLineTravelS,    RedLineDwellS    },
  { "BL", { BlueLineTrack1Domains,   BlueLineTrack2Domains   }, { BlueLineTrack1StationSegments,   BlueLineTrack2StationSegments   }, BlueLineLEDArray,   BlueLineStationLEDPosition,   BlueLineNumStationsInLine,   Blue_Num_LED_Domains,   BlueLineTravelS,   BlueLineDwellS   },
  { "GR", { GreenLineTrack1Domains,  GreenLineTrack2Domains  }, { GreenLineTrack1StationSegments,  GreenLineTrack2StationSegments  }, GreenLineLEDArray,  GreenLineStationLEDPosition,  GreenLineNumStationsInLine,  Green_Num_LED_Domains,  GreenLineTravelS,  GreenLineDwellS  },
  { "OR", { OrangeLineTrack1Domains, OrangeLineTrack2Domains }, { OrangeLineTrack1StationSegments, OrangeLineTrack2StationSegments }, OrangeLineLEDArray, OrangeLineStationLEDPosition, OrangeLineNumStationsInLine, Orange_Num_LED_Domains, OrangeLineTravelS, OrangeLineDwellS },
  { "YL", { YellowLineTrack1Domains, YellowLineTrack2Domains }, { YellowLineTrack1StationSegments, YellowLineTrack2StationSegments }, YellowLineLEDArray, YellowLineStationLEDPosition, YellowLineNumStationsInLine, Yellow_Num_LED_Domains, YellowLineTravelS, YellowLineDwellS },
};

// sim timetable sizing: a run has one dwell per station and one travel per
// domain (stations = domains + 1, enforced in asl_map_data.h)
static constexpr size_t aslMaxOf(size_t a, size_t b) { return a > b ? a : b; }
static constexpr size_t ASL_MAX_STATIONS = aslMaxOf(aslMaxOf(aslMaxOf(RedLineNumStationsInLine, BlueLineNumStationsInLine),
                                                             aslMaxOf(GreenLineNumStationsInLine, OrangeLineNumStationsInLine)),
                                                    YellowLineNumStationsInLine);
static constexpr size_t ASL_MAX_PHASES = 2 * ASL_MAX_STATIONS - 1;
// travel speed for a domain with no measured time yet; matches the old
// hand-made timetables (3 s per track circuit)
static constexpr uint32_t ASL_PLACEHOLDER_S_PER_CIRCUIT = 3;

// ---- moving-train sprites ----
// Trains are not baked into the frames; each is a sprite gliding toward the
// fractional LED position of its latest data point, re-targeted every plot
// cycle and rendered at the strip frame rate (one LED, crossfading to the next
// inside the "Train Crossfade" window).
#define ASL_MAX_SPRITES    256   // active trains (<= MAX_TRAINS) + fading ghosts
#define ASL_TELEPORT_LEDS  8.0f  // moves larger than this dissolve instead of gliding
#define ASL_DEF_AA_GAMMA   2.2f  // default perceptual boost exponent ("Gamma" setting)
#define ASL_DEF_CROSSFADE  0.25f // default "Train Crossfade" window, fraction of one LED
#define ASL_DEF_HOP_BELOW  12    // default "Hop Below Brightness" (0 = never hop)
#define ASL_GLIDE_SLACK_MS 300   // glides last this much longer than the refresh interval, so a
                                 // late update (loop deferred while the strip draws) never leaves
                                 // a train parked; it just lags its data point very slightly
// live data: WMATA refreshes positions less often than we poll (and only in
// whole circuits), so glides span the measured feed interval instead of the
// poll interval (see UsermodASL::feedIntervalMs)
#define ASL_FEED_DEF_MS    10000 // assumed WMATA refresh interval until one is measured
#define ASL_FEED_MAX_MS    30000 // cap for the measured interval (glide length)
#define ASL_FEED_STALE_MS  60000 // no good data for this long: clear live trains from the map

// runtime-tunable sprite settings (usermod settings page)
static float    aslGamma     = ASL_DEF_AA_GAMMA;  // anti-alias brightness curve, 1.0 = linear
static float    aslCrossfade = ASL_DEF_CROSSFADE; // LED-to-LED handover window: 0 = hop, 1 = full blend
static uint8_t  aslHopBelowBri = ASL_DEF_HOP_BELOW; // below this shown brightness the handover is a hop

enum : uint8_t { ASL_SPR_FREE = 0, ASL_SPR_LIVE = 1, ASL_SPR_GHOST = 2 };

struct AslSprite {
  uint8_t  mode;         // ASL_SPR_*
  uint8_t  lineIdx;      // ASL_LINE_*
  uint8_t  dir;          // track/direction number, part of the identity key
  uint8_t  missed;       // consecutive plot cycles without a data point
  bool     seen;         // matched during the current reconciliation pass
  uint32_t id;           // train ID (live: WMATA TrainId; sim: departure index + 1)
  float    startPos;     // glide origin (fractional LED)
  float    targetPos;    // glide destination (fractional LED)
  uint32_t moveStartMs;
  uint32_t moveDurMs;    // 0 = parked at targetPos
  uint32_t fadeStartMs;  // spawn (fade-in) or ghost (fade-out) start
};

static AslSprite aslSprites[ASL_MAX_SPRITES];
static uint8_t aslPerceptLUT[256]; // coverage -> blend amount

// perceptual anti-alias curve: boost fractional coverage by 1/gamma so a train
// split across two LEDs reads as bright as one fully lit LED; rebuilt whenever
// the Gamma setting changes
static void aslBuildPerceptLUT() {
  for (int i = 0; i < 256; i++)
    aslPerceptLUT[i] = (uint8_t)(powf((float)i / 255.0f, 1.0f / aslGamma) * 255.0f + 0.5f);
}

// sprite position along its current glide, at constant speed. Each glide is
// timed to last until the next data point is expected (sim: the refresh
// interval; live: the measured WMATA feed interval), so a train is normally
// still moving when its next position arrives and motion stays continuous.
// (Easing was dropped: braking to a stop at every data point made trains
// stop-and-go.)
static float aslSpritePos(const AslSprite& s, uint32_t nowMs) {
  if (s.moveDurMs == 0) return s.targetPos;
  uint32_t el = nowMs - s.moveStartMs;
  if (el >= s.moveDurMs) return s.targetPos;
  float t = (float)el / (float)s.moveDurMs;
  return s.startPos + (s.targetPos - s.startPos) * t;
}

// Train appear/vanish fade time (also each half of a dissolve). Follows WLED's
// own Transition Time (Config -> LED Preferences) so there is one place to tune
// how soft changes are on this device. Uses the stored default, not the live
// transitionDelay, which a single request ("tt", the main UI's transition box)
// can change temporarily. Clamped so a very long transition cannot keep
// vanished trains on the map.
static uint32_t aslFadeMs() {
  return (transitionDelayDefault > 5000) ? 5000 : transitionDelayDefault;
}

// current fade alpha (0-255): rises after spawn, falls after ghosting
static uint8_t aslSpriteAlpha(const AslSprite& s, uint32_t nowMs) {
  const uint32_t fade = aslFadeMs();
  uint32_t el = nowMs - s.fadeStartMs;
  uint32_t a  = (fade == 0 || el >= fade) ? 255 : (el * 255) / fade;
  return (s.mode == ASL_SPR_GHOST) ? (uint8_t)(255 - a) : (uint8_t)a;
}

// fractional LED for one track's data point: station snap (+/-1 circuit)
// first, then linear interpolation within the containing domain. Circuits are
// float: live data is integer-valued, the sim interpolates between circuits.
// The snap must stay at +/-1 — station circuits sit in the gaps between
// domains, so it is what catches positions there (the sim parks dwelling
// trains exactly on the station circuit, live data reports it directly).
static bool aslTargetForTrack(const AslLineDef& L, uint8_t track, float circuit, float& out) {
  const uint16_t* segs = L.stationSegs[track];
  for (uint16_t x = 0; x < L.numStations; x++) {
    if (fabsf(circuit - (float)segs[x]) <= 1.0f) {
      out = (float)L.stationLEDPos[x];
      return true;
    }
  }
  const uint16_t (*dom)[2] = L.domains[track];
  for (uint16_t y = 0; y < L.numDomains; y++) {
    if (circuit >= dom[y][0] && circuit <= dom[y][1]) {
      uint16_t c0 = dom[y][0], c1 = dom[y][1];
      uint16_t l0 = L.ledArray[y][0], l1 = L.ledArray[y][1];
      out = (c1 > c0) ? (float)l0 + (circuit - (float)c0) * (float)(l1 - l0) / (float)(c1 - c0)
                      : 0.5f * (float)(l0 + l1);
      return true;
    }
  }
  return false;
}

static bool aslTargetLED(uint8_t lineIdx, float circuit, float& out) {
  const AslLineDef& L = aslLines[lineIdx];
  return aslTargetForTrack(L, 0, circuit, out) || aslTargetForTrack(L, 1, circuit, out);
}

// AI: below section was generated by an AI
// Sprite identity for a live train. WMATA sends TrainId as a string ("086"),
// so reading it as a number gave every train ID 0: all trains on a line and
// direction then shared one sprite, which jumped (dissolved) from train to
// train each refresh - a flash of trains, then darkness with ~one train left
// per line/direction. Numeric strings are converted ("086" -> 86); anything
// else is hashed (djb2) so it still gets a stable, distinct ID; plain numbers
// are accepted too.
static uint32_t aslTrainIdFrom(JsonVariantConst v) {
  if (v.is<const char*>()) {
    const char* s = v.as<const char*>();
    char* end = nullptr;
    uint32_t n = strtoul(s, &end, 10);
    if (*s && end && *end == '\0') return n;
    uint32_t h = 5381;
    while (*s) h = h * 33 + (uint8_t)*s++;
    return h;
  }
  return v.as<uint32_t>();
}
// AI: end

static int8_t aslLineIndex(const char* code) {
  for (uint8_t i = 0; i < ASL_NUM_LINES; i++) if (strncmp(code, aslLines[i].code, 2) == 0) return (int8_t)i;
  return -1;
}

static AslSprite* aslFindSprite(uint8_t lineIdx, uint8_t dir, uint32_t id) {
  for (auto &s : aslSprites)
    if (s.mode == ASL_SPR_LIVE && s.lineIdx == lineIdx && s.dir == dir && s.id == id) return &s;
  return nullptr;
}

static void aslSpawnSprite(uint8_t lineIdx, uint8_t dir, uint32_t id, float pos, uint32_t nowMs) {
  for (auto &s : aslSprites) {
    if (s.mode != ASL_SPR_FREE) continue;
    s = { ASL_SPR_LIVE, lineIdx, dir, 0, true, id, pos, pos, nowMs, 0, nowMs };
    return;
  } // table full: the train simply appears on a later cycle
}

static void aslGhostSprite(AslSprite& s, uint32_t nowMs) {
  s.startPos = s.targetPos = aslSpritePos(s, nowMs); // freeze in place while fading out
  s.moveDurMs   = 0;
  s.mode        = ASL_SPR_GHOST;
  s.fadeStartMs = nowMs;
  s.seen        = false;
}

// ---- effects: paint scenery from the frame, then the train sprites on top ----
static void aslDrawFrame(const uint8_t* frame, uint16_t frameLen, uint8_t lineIdx) {
  const int len = SEGLEN;
  for (int i = 0; i < len; i++) {
    uint8_t m = (i < frameLen) ? frame[i] : ASL_PX_TRACK;
    SEGMENT.setPixelColor(i, SEGCOLOR(m));
  }

  const uint32_t trainC = SEGCOLOR(ASL_PX_TRAIN);
  const uint32_t nowMs  = millis();
  // Hop Below Brightness: LEDs take 8-bit values and brightness is applied
  // after this effect, so at brightness 10 a train LED has only ~10 output
  // levels and each low step (1 -> 2 -> 3) is a large visible jump; a crossfade
  // then reads as a stutter. Below the threshold, compared against the
  // brightness this line actually shows (global brightness x segment
  // opacity), the handover becomes a clean hop instead.
  const uint8_t shownBri  = (uint8_t)(((uint16_t)strip.getBrightness() * SEGMENT.opacity) / 255);
  const float   crossfade = (shownBri < aslHopBelowBri) ? 0.0f : aslCrossfade;
  for (unsigned n = 0; n < ASL_MAX_SPRITES; n++) {
    const AslSprite& s = aslSprites[n];
    if (s.mode == ASL_SPR_FREE || s.lineIdx != lineIdx) continue;
    uint8_t alpha = aslSpriteAlpha(s, nowMs);
    if (alpha == 0) continue;
    float pos  = aslSpritePos(s, nowMs);
    int   i0   = (int)floorf(pos);
    float frac = pos - (float)i0;
    // Train Crossfade: trains move slowly (often several seconds per LED), so
    // a full two-LED blend would show most trains as a two-LED smear. Only a
    // window of this width around the midpoint between LEDs is blended; outside
    // it the train sits on one LED. 0 = hard hop at the midpoint (nearest LED),
    // 1 = full linear blend across the whole gap.
    if (crossfade <= 0.0f) {
      frac = (frac < 0.5f) ? 0.0f : 1.0f;
    } else if (crossfade < 1.0f) {
      frac = (frac - 0.5f) / crossfade + 0.5f;
      frac = (frac < 0.0f) ? 0.0f : (frac > 1.0f ? 1.0f : frac);
    }
    // split coverage * fade alpha across the two straddled LEDs, boosted
    // through the perceptual LUT so apparent brightness holds mid-glide
    unsigned w0 = (unsigned)((1.0f - frac) * alpha + 0.5f);
    unsigned w1 = (unsigned)(frac * alpha + 0.5f);
    if (w0 > 0 && i0 >= 0 && i0 < len)
      SEGMENT.setPixelColor(i0, color_blend(SEGMENT.getPixelColor(i0), trainC, aslPerceptLUT[w0 > 255 ? 255 : w0]));
    if (w1 > 0 && i0 + 1 >= 0 && i0 + 1 < len)
      SEGMENT.setPixelColor(i0 + 1, color_blend(SEGMENT.getPixelColor(i0 + 1), trainC, aslPerceptLUT[w1 > 255 ? 255 : w1]));
  }
}

static void mode_asl_red(void)    { aslDrawFrame(RedFrame,    sizeof(RedFrame),    ASL_LINE_RED);    }
static void mode_asl_blue(void)   { aslDrawFrame(BlueFrame,   sizeof(BlueFrame),   ASL_LINE_BLUE);   }
static void mode_asl_green(void)  { aslDrawFrame(GreenFrame,  sizeof(GreenFrame),  ASL_LINE_GREEN);  }
static void mode_asl_orange(void) { aslDrawFrame(OrangeFrame, sizeof(OrangeFrame), ASL_LINE_ORANGE); }
static void mode_asl_yellow(void) { aslDrawFrame(YellowFrame, sizeof(YellowFrame), ASL_LINE_YELLOW); }

static const char _data_FX_ASL_RED[]    PROGMEM = "ASL Red Line@;Train,Station,Track;;1";
static const char _data_FX_ASL_BLUE[]   PROGMEM = "ASL Blue Line@;Train,Station,Track;;1";
static const char _data_FX_ASL_GREEN[]  PROGMEM = "ASL Green Line@;Train,Station,Track;;1";
static const char _data_FX_ASL_ORANGE[] PROGMEM = "ASL Orange Line@;Train,Station,Track;;1";
static const char _data_FX_ASL_YELLOW[] PROGMEM = "ASL Yellow Line@;Train,Station,Track;;1";

// AI: below section was generated by an AI
// ---- status LED effect ----
// "ASL - Status LED" shows the map's health on a status LED (here the S3 board's
// onboard RGB LED on GPIO48, set up as its own 1-LED strip). Assign the effect
// to a segment covering that LED. It writes plain full-scale colors and leaves
// dimming to WLED, so global brightness and segment opacity apply exactly as
// they do for the train lines. The usermod updates aslStatus every loop;
// highest priority first:
enum : uint8_t {
  ASL_ST_OFFLINE_NO_CLOCK = 0, // red, slow blink: no Wi-Fi and the RTC has not set the clock (missing/unset)
  ASL_ST_ATTENTION,            // amber, fast blink: clock not set yet, or live mode without working data
  ASL_ST_SIM_TEST_TIME,        // purple: sim running on a test time, not real time
  ASL_ST_LIVE_OK,              // green: live mode, WMATA data arriving
  ASL_ST_SIM_RTC,              // cyan: sim on real time kept by the RTC (offline, as intended)
  ASL_ST_SIM_NETWORK,          // blue: sim on real time from NTP / network / browser
};
static uint8_t aslStatus = ASL_ST_ATTENTION; // until the first status update

static void mode_asl_status(void) {
  static const uint32_t colors[] = { RGBW32(255, 0, 0, 0), RGBW32(255, 120, 0, 0), RGBW32(140, 0, 255, 0),
                                     RGBW32(0, 255, 0, 0), RGBW32(0, 255, 255, 0), RGBW32(0, 0, 255, 0) };
  uint32_t c = colors[aslStatus < sizeof(colors) / sizeof(colors[0]) ? aslStatus : ASL_ST_ATTENTION];
  const uint32_t now = millis();
  if (aslStatus == ASL_ST_OFFLINE_NO_CLOCK && (now / 1000) % 2) c = 0; // 1 s on / 1 s off
  if (aslStatus == ASL_ST_ATTENTION        && (now /  250) % 2) c = 0; // 4 blinks per 2 s
  SEGMENT.fill(c);
}
// named so it sorts first among the ASL effects in the UI (the effect list is
// sorted with localeCompare, which puts punctuation before letters) instead of
// landing between "ASL Red Line" and "ASL Yellow Line"; presets use the ID, not the name
static const char _data_FX_ASL_STATUS[] PROGMEM = "ASL - Status LED@;;;1";
// AI: end

// AI: below section was generated by an AI
// ---- fixed effect IDs ----
// Presets store effects by number, so the ASL effects must keep the same IDs
// whatever build flags are used. Registering with id 255 ("first free slot")
// is NOT stable: WLED pre-fills the table with reserved slots and disabling
// effect groups (e.g. WLED_DISABLE_2D) frees lower slots, which moved these
// effects and made saved presets fall back to Solid at full brightness on
// every line (enough current to trip the brownout detector).
// 142, 169, 170 and 171 are the only IDs below MODE_COUNT that no stock
// effect uses under any flag combination (FX.h: removed/never-added effects);
// Yellow and Status are appended directly after the table (MODE_COUNT = 220,
// 221), which is stable as long as no other usermod appends effects first.
// These match the IDs the effects got in the earlier 2D-enabled builds, so
// presets saved then keep working.
#define ASL_FX_RED    142
#define ASL_FX_BLUE   169
#define ASL_FX_GREEN  170
#define ASL_FX_ORANGE 171
#define ASL_FX_YELLOW MODE_COUNT        // 220: first slot after the stock table
#define ASL_FX_STATUS (MODE_COUNT + 1)  // 221
static_assert(MODE_COUNT == 220, "WLED effect table size changed: re-check ASL_FX_* IDs (presets depend on them)");

// register at a fixed ID; if that slot is ever taken (e.g. by a future WLED
// update) fall back to any free slot so the effect still exists, and log it
static bool aslFxIdsOk = true; // false if any effect missed its fixed ID (shown in the Info panel)
static void aslAddEffect(uint8_t id, void (*fn)(void), const char* data) { // fn: an effect function (WS2812FX::mode_ptr is private)
  uint8_t got = strip.addEffect(id, fn, data);
  if (got == 255) got = strip.addEffect(255, fn, data);
  if (got != id) {
    aslFxIdsOk = false;
    DEBUG_PRINTF_P(PSTR("ASL: effect wanted ID %u, got %u - presets need updating\n"), id, got);
  }
}
// AI: end


class UsermodASL : public Usermod {
  private:
    static const uint16_t MAX_TRAINS = 256; // all 10 tracks at rush headway fit comfortably

    // factory defaults — single source of truth: they initialize the members
    // below, back every readFromConfig fallback, and thus pre-populate the
    // settings boxes on a device with no saved config
    // WMATA weekday hours: open 05:00, close midnight (00:00 wraps via the
    // modulo schedule math; Fri/Sat really close at 02:00 but the sim has one schedule)
    static const uint32_t DEF_OPEN_S     = 18000;  // 05:00
    static const uint32_t DEF_CLOSE_S    = 0;      // 00:00 = midnight
    static const uint32_t DEF_HEADWAY_S  = 360;    // 6 min
    static const uint32_t DEF_DWELL_S    = 25;     // fallback dwell; measured dwells are 15-45 s
    static const uint32_t MAX_DWELL_S    = 600;
    static const uint32_t DEF_REFRESH_MS = 15000;  // WMATA refreshes each train about every 15 s; polling
                                                   // faster makes live trains glide, then wait for data
    // rush defaults per WMATA's published FY2026 peak service (7-9am, 4-6pm,
    // Red line "at least every four minutes")
    static const uint32_t DEF_AM_RUSH_START_S = 25200; // 07:00
    static const uint32_t DEF_AM_RUSH_END_S   = 32400; // 09:00
    static const uint32_t DEF_PM_RUSH_START_S = 57600; // 16:00
    static const uint32_t DEF_PM_RUSH_END_S   = 64800; // 18:00
    static const uint32_t DEF_RUSH_HEADWAY_S  = 240;   // 4 min

    bool enabled = true;
    bool initDone = false;
    unsigned long lastTime = 0;

    // ---- config (usermod settings page) ----
    // times are stored internally as seconds; in cfg.json open/close are "HH:MM"
    // strings and headway is minutes (decimals ok), converted in read/addToConfig
    bool     simModeEnable = true;
    String   serverAddress = "http://api.wmata.com/TrainPositions/TrainPositions?contentType=json";
    String   apiKey = "";
    uint32_t systemFirstTrainTime = DEF_OPEN_S;    // second of day the first train departs
    uint32_t systemLastTrainTime  = DEF_CLOSE_S;   // second of day the last train departs
    uint32_t headwayTimeSeconds   = DEF_HEADWAY_S; // seconds between train departures
    uint32_t amRushStartTime = DEF_AM_RUSH_START_S; // rush windows: same-day seconds; start >= end disables the window
    uint32_t amRushEndTime   = DEF_AM_RUSH_END_S;
    uint32_t pmRushStartTime = DEF_PM_RUSH_START_S;
    uint32_t pmRushEndTime   = DEF_PM_RUSH_END_S;
    uint32_t rushHeadwayTimeSeconds = DEF_RUSH_HEADWAY_S; // 0 = no rush service
    uint32_t stationDwellTimeS    = DEF_DWELL_S;   // sim: dwell at stations without a measured value (terminals, data gaps)
    uint32_t plotRefreshIntervalMs = DEF_REFRESH_MS; // data refresh + glide time; settings page shows seconds

    // ---- runtime state ----
    uint32_t secondOfDay = 0;               // the sim's time of day: real local time + simOffsetS
    uint32_t simOffsetS  = 0;               // sim test offset (0..86399 s); runtime only, never saved,
                                            // never touches the real clock or the RTC chip
    bool     lastFetchOk = false;           // live mode: did the last WMATA fetch succeed? (status LED)
    // live feed tracking: WMATA refreshes less often than we poll, so only real
    // changes move trains, and glides span the measured refresh interval
    bool     feedChanged      = false;           // last fetch brought new positions
    uint32_t feedSig          = 0;               // fingerprint of the last positions seen
    uint32_t lastFeedChangeMs = 0;               // when they last changed
    uint32_t lastGoodFetchMs  = 0;               // last successful fetch
    uint32_t feedIntervalMs   = ASL_FEED_DEF_MS; // smoothed time between real feed updates

    // ---- Info panel diagnostics (read-only bookkeeping, no effect on behaviour) ----
    enum : uint8_t { FETCH_NONE, FETCH_OK, FETCH_NO_KEY, FETCH_NO_WIFI, FETCH_CONNECT, FETCH_HTTP, FETCH_PARSE };
    uint8_t  fetchResult    = FETCH_NONE; // outcome of the last live fetch attempt
    int      fetchHttpCode  = 0;          // HTTP status (or HTTPClient error) of a failed fetch
    uint32_t lastFetchMs    = 0;          // when the last fetch was attempted
    uint32_t fetchDurMs     = 0;          // how long it blocked the main loop
    uint32_t apiCalls       = 0;          // WMATA requests since boot
    uint16_t statFeed = 0, statDrawn = 0, statOffMap = 0, statOtherLine = 0, statNonRevenue = 0;
    uint16_t statPerLine[ASL_NUM_LINES] = {0}; // trains drawn per line in the last sprite update
    unsigned long lastSeenNtpSync = NTP_NEVER;  // last value of WLED's ntpLastSyncTime we saw
    unsigned long lastNtpOkMs     = 0;          // when NTP last actually succeeded
    bool          ntpOkSeen       = false;
    bool     rtcSeen     = false;           // has the RTC set the clock since boot? (status LED)
    bool     delaysRacked = false;          // sim timetables built for the current settings?
    uint32_t phaseEndS[ASL_NUM_LINES][ASL_MAX_PHASES]; // per line: cumulative end time of each dwell/travel phase (Track1 order)
    uint32_t runS[ASL_NUM_LINES];                      // per line: end-to-end run time in seconds

    // train table (compact; one entry per active train this cycle)
    uint16_t numTrains = 0;
    uint32_t trainId[MAX_TRAINS];
    float    trainCircuit[MAX_TRAINS]; // fractional: sim interpolates between circuits, live is integer-valued
    uint8_t  trainDirection[MAX_TRAINS];
    uint8_t  trainCars[MAX_TRAINS];
    uint8_t  trainSecondsAtLoc[MAX_TRAINS];
    char     trainLine[MAX_TRAINS][3];
    bool     trainNormal[MAX_TRAINS];

    static const char _name[];
    static const char _enabled[];

    // "HH:MM" -> second of day; returns fallback on malformed/out-of-range input
    static uint32_t parseHHMM(const char* s, uint32_t fallback) {
      int h = -1, m = -1;
      if (!s || sscanf(s, "%d:%d", &h, &m) != 2) return fallback;
      if (h < 0 || h > 23 || m < 0 || m > 59) return fallback;
      return h * 3600UL + m * 60UL;
    }

    // real local time of day from WLED's clock (NTP, RTC or browser-set)
    static uint32_t realSecondOfDay() {
      return hour(localTime) * 3600UL + minute(localTime) * 60UL + second(localTime);
    }

    // AI: below section was generated by an AI
    // Human-readable name for WLED's current time source. Toki ranks sources
    // by accuracy (wled00/src/dependencies/toki/Toki.h); the RTC usermod sets
    // TOKI_TS_RTC at boot, the web UI and "Set clock from this device" set
    // TOKI_TS_JSON, NTP sets TOKI_TS_NTP.
    static const __FlashStringHelper* timeSourceName(uint8_t src) {
      if (src == TOKI_TS_NONE)    return F("not set");
      if (src >= TOKI_TS_NTP)     return F("NTP");
      if (src >= TOKI_TS_UDP_NTP) return F("network sync");
      if (src >= TOKI_TS_JSON)    return F("browser / API");
      if (src >= TOKI_TS_RTC)     return F("RTC");
      return F("low-accuracy sync");
    }
    // AI: end

    static void formatHHMM(uint32_t secOfDay, char* buf, size_t len) {
      snprintf(buf, len, "%02u:%02u", (unsigned)(secOfDay / 3600UL) % 24, (unsigned)((secOfDay / 60UL) % 60));
    }

    void clearTrains() { numTrains = 0; }

    void injectSimTrain(uint16_t simIdx, uint8_t dir, float circuit, const char* lineCode) {
      if (numTrains >= MAX_TRAINS) return;
      uint16_t i = numTrains++;
      trainId[i]           = simIdx + 1;
      trainCircuit[i]      = circuit;
      trainDirection[i]    = dir;
      trainCars[i]         = 8;
      trainSecondsAtLoc[i] = 2;
      strlcpy(trainLine[i], lineCode, sizeof(trainLine[i]));
      trainNormal[i]       = true;
    }

    // headway in effect for a departure at this second of day: rush windows
    // shorten it; a window with start >= end is disabled, rush headway 0
    // disables rush entirely
    uint32_t headwayAt(uint32_t sod) const {
      if (rushHeadwayTimeSeconds == 0) return headwayTimeSeconds;
      if ((amRushStartTime < amRushEndTime && sod >= amRushStartTime && sod < amRushEndTime) ||
          (pmRushStartTime < pmRushEndTime && sod >= pmRushStartTime && sod < pmRushEndTime))
        return rushHeadwayTimeSeconds;
      return headwayTimeSeconds;
    }

    // AI: below section was generated by an AI
    // Build each line's Track1 timeline from the measured timing tables
    // (asl_timing_data.h) and the fallback dwell setting. A run alternates
    // dwell at station 0, travel over domain 0, dwell at station 1, ... dwell
    // at the last station; phaseEndS[line][p] holds the cumulative end time of
    // phase p, so even p = dwell at station p/2, odd p = travel over domain p/2.
    // Track2 needs no table of its own: it is the same timeline run backwards.
    // Called again whenever settings are saved (delaysRacked is cleared in
    // readFromConfig), so a new fallback dwell applies without a reboot.
    void rackTimetables() {
      for (uint8_t li = 0; li < ASL_NUM_LINES; li++) {
        const AslLineDef& L = aslLines[li];
        uint32_t acc = 0;
        for (uint16_t k = 0; k < L.numStations; k++) {
          acc += L.dwellS[k] ? L.dwellS[k] : stationDwellTimeS; // 0 = not measured (terminals, gaps)
          phaseEndS[li][2 * k] = acc;
          if (k < L.numDomains) {
            uint32_t travel = L.travelS[k];
            if (travel == 0) {
              // not measured yet: keep the old hand-made tables' speed so the
              // gap neither freezes trains nor teleports them
              const uint16_t* d = L.domains[0][k];
              uint32_t circuits = ((d[1] >= d[0]) ? d[1] - d[0] : d[0] - d[1]) + 1;
              travel = circuits * ASL_PLACEHOLDER_S_PER_CIRCUIT;
            }
            acc += travel;
            phaseEndS[li][2 * k + 1] = acc;
          }
        }
        runS[li] = acc;
        DEBUG_PRINTF_P(PSTR("ASL: %s run %u s\n"), L.code, (unsigned)acc);
      }
      delaysRacked = true;
    }

    // Simulate all trains currently en route on one track (0 = Track1,
    // 1 = Track2) of one line. Trains depart from open to close, each gap set
    // by the headway in effect at the departure it follows (rush windows
    // shorten it). A train's position comes from the phase of the timetable
    // that brackets "now - departure": dwelling trains sit on their station
    // circuit, moving trains are interpolated across the domain's circuits.
    // All schedule math is modulo 24h, so service may span midnight (close
    // before open, open == close = 24h) and late runs keep going past the
    // date line.
    void offlineSimTrains(uint8_t li, uint8_t track) {
      const AslLineDef& L = aslLines[li];
      const uint32_t runDuration = runS[li]; // end-to-end run time, both tracks
      if (runDuration == 0 || headwayTimeSeconds == 0) return;
      const uint16_t lastPhase = 2 * L.numStations - 2;
      uint32_t opDuration = (systemLastTrainTime > systemFirstTrainTime)
                          ? systemLastTrainTime - systemFirstTrainTime
                          : 86400UL - systemFirstTrainTime + systemLastTrainTime;

      // a departure exactly at close is the last train, except in 24h service
      // where elapsed == 86400 is the first departure again (duplicate train)
      uint32_t lastElapsed = (opDuration >= 86400UL) ? opDuration - 1 : opDuration;

      uint32_t elapsed = 0; // seconds from open to this departure
      for (uint32_t i = 0; elapsed <= lastElapsed && i < 4096; i++) {
        uint32_t departure = (systemFirstTrainTime + elapsed) % 86400UL;
        elapsed += headwayAt(departure);
        uint32_t t = (secondOfDay + 86400UL - departure) % 86400UL; // seconds into this train's run, wrap-safe
        if (t == 0 || t >= runDuration) continue;

        // Track1 runs the timeline forward from station 0; Track2 starts at
        // the far end, so its position at time t is Track1's at runDuration - t
        uint32_t s = (track == 0) ? t : runDuration - t;
        uint16_t p = 0;
        while (p < lastPhase && s > phaseEndS[li][p]) p++;
        uint32_t p0  = p ? phaseEndS[li][p - 1] : 0;
        uint32_t len = phaseEndS[li][p] - p0;

        float circuit;
        if ((p & 1) == 0) {
          // dwelling: park on the station circuit; the renderer's +/-1 station
          // snap puts it on the station LED
          circuit = (float)L.stationSegs[track][p / 2];
        } else {
          // moving: fraction of the domain covered, measured in the Track1
          // (LED-ascending) sense, which is how {first,last} map to LEDs on
          // both tracks. For Track2 the mirrored time makes it run downward.
          float frac = len ? (float)(s - p0) / (float)len : 0.0f;
          const uint16_t* d = L.domains[track][p / 2];
          circuit = (float)d[0] + frac * ((float)d[1] - (float)d[0]);
        }
        injectSimTrain(i, track + 1, circuit, L.code);
      }
    }
    // AI: end

    // AI: below section was generated by an AI
    // Work out what the status LED shows (see ASL_ST_* for the colors).
    // "RTC working" means the RTC usermod actually set the clock this boot
    // (time source TOKI_TS_RTC seen at least once): a missing chip disables
    // that usermod and an unset chip reports no time, so neither counts. Once
    // seen it stays true, because a later NTP or browser sync replaces the
    // time source while the RTC is still there to fall back on.
    void updateStatus() {
      const uint8_t src = toki.getTimeSource();
      if (src == TOKI_TS_RTC) rtcSeen = true;
      // NTP bookkeeping for the Info panel: WLED sets ntpLastSyncTime to "now"
      // on a successful sync, but to a past "pause" value after a DNS failure
      // (ntp.cpp), so only an update that lands at the current time counts
      if (ntpLastSyncTime != lastSeenNtpSync) {
        lastSeenNtpSync = ntpLastSyncTime;
        if (ntpLastSyncTime != NTP_NEVER && millis() - ntpLastSyncTime < 5000) {
          lastNtpOkMs = ntpLastSyncTime;
          ntpOkSeen   = true;
        }
      }
      const bool online = WLED_CONNECTED;
      if (!online && !rtcSeen)
        aslStatus = ASL_ST_OFFLINE_NO_CLOCK;
      else if (src == TOKI_TS_NONE || (!simModeEnable && !(online && lastFetchOk)))
        aslStatus = ASL_ST_ATTENTION;
      else if (simModeEnable && simOffsetS)
        aslStatus = ASL_ST_SIM_TEST_TIME;
      else if (!simModeEnable)
        aslStatus = ASL_ST_LIVE_OK;
      else if (src == TOKI_TS_RTC || !online)
        aslStatus = ASL_ST_SIM_RTC;
      else
        aslStatus = ASL_ST_SIM_NETWORK;
    }
    // AI: end

    // fetch live train positions from the WMATA API into the train table
    void getWMATAData() {
      lastFetchOk = false; // set true only when a full, parsed response arrives (status LED)
      feedChanged = false; // set true only when the positions differ from the last fetch
#ifdef ESP32
      if (apiKey.length() == 0) { fetchResult = FETCH_NO_KEY; return; }
      HTTPClient http;
      http.setConnectTimeout(3000);
      http.setTimeout(5000);
      String url = serverAddress + "&api_key=" + apiKey;
      if (!http.begin(url)) { fetchResult = FETCH_CONNECT; fetchHttpCode = 0; return; }
      apiCalls++;
      int code = http.GET();
      if (code != HTTP_CODE_OK) {
        DEBUG_PRINTF_P(PSTR("ASL: WMATA HTTP error %d\n"), code);
        fetchResult   = (code < 0) ? FETCH_CONNECT : FETCH_HTTP; // negative = HTTPClient error (no connection, timeout)
        fetchHttpCode = code;
        http.end();
        return;
      }
      String payload = http.getString(); // handles chunked replies; ~20-30 KB for ~120-170 positions
      http.end();

      // AI: below section was generated by an AI
      // Parse only the fields used below. The full feed (~9 fields per train,
      // ~120 positions off-peak, more at rush) overflowed the old fixed 24 KB
      // document; filtered, one train costs ~140 bytes (7 member slots plus a
      // few short strings, keys deduplicated), so this size covers MAX_TRAINS.
      StaticJsonDocument<256> filter;
      JsonObject f = filter["TrainPositions"].createNestedObject();
      f["TrainId"] = true;  f["CircuitId"] = true;  f["DirectionNum"] = true; f["CarCount"] = true;
      f["SecondsAtLocation"] = true; f["LineCode"] = true; f["ServiceType"] = true;
      DynamicJsonDocument doc(MAX_TRAINS * 160);
      DeserializationError err = deserializeJson(doc, payload, DeserializationOption::Filter(filter));
      if (err) {
        DEBUG_PRINTF_P(PSTR("ASL: JSON parse failed: %s (payload %u bytes)\n"), err.c_str(), payload.length());
        fetchResult = FETCH_PARSE;
        return;
      }
      // AI: end
      JsonArray positions = doc["TrainPositions"];
      uint16_t n = positions.size();
      if (n > MAX_TRAINS) n = MAX_TRAINS;
      for (uint16_t i = 0; i < n; i++) {
        JsonObject t = positions[i];
        trainId[i]           = aslTrainIdFrom(t["TrainId"]);
        trainCircuit[i]      = (float)(t["CircuitId"] | 0UL);
        trainDirection[i]    = t["DirectionNum"] | 0;
        trainCars[i]         = t["CarCount"] | 0;
        uint32_t atLoc       = t["SecondsAtLocation"] | 0UL; // feed can report e.g. 9990
        trainSecondsAtLoc[i] = (atLoc > 255) ? 255 : (uint8_t)atLoc;
        strlcpy(trainLine[i], t["LineCode"] | "", sizeof(trainLine[i]));
        trainNormal[i]       = (strcmp(t["ServiceType"] | "", "Normal") == 0);
      }
      numTrains = n;
      lastFetchOk = true;
      fetchResult = FETCH_OK;

      // AI: below section was generated by an AI
      // Did WMATA actually refresh? Fingerprint (FNV-1a) every train's ID,
      // direction and circuit; an identical fingerprint means this poll saw the
      // same snapshot as the last one. The time between real changes, smoothed
      // (3/4 old + 1/4 new), is the feed's refresh interval - measured across
      // the whole feed, so trains dwelling at stations don't distort it.
      const uint32_t nowMs = millis();
      uint32_t sig = 2166136261UL;
      for (uint16_t i = 0; i < n; i++) {
        uint32_t v[3] = { trainId[i], (uint32_t)trainDirection[i], (uint32_t)trainCircuit[i] };
        for (uint32_t x : v) { sig ^= x; sig *= 16777619UL; }
      }
      lastGoodFetchMs = nowMs;
      if (sig != feedSig) {
        if (lastFeedChangeMs) {
          uint32_t iv = nowMs - lastFeedChangeMs;
          if (iv >= 1000 && iv <= 2 * ASL_FEED_MAX_MS) feedIntervalMs = (feedIntervalMs * 3 + iv) / 4;
        }
        lastFeedChangeMs = nowMs;
        feedSig          = sig;
        feedChanged      = true;
      }
      // AI: end
      DEBUG_PRINTF_P(PSTR("ASL: fetched %u trains\n"), numTrains);
#endif
    }

    void clearFrame(uint8_t frame[], uint16_t frameLen) {
      memset(frame, ASL_PX_TRACK, frameLen);
    }

    void plotStations(uint8_t frame[], uint16_t frameLen, const uint16_t stationLEDPos[], uint16_t numStations) {
      for (uint16_t i = 0; i < numStations; i++) {
        if (stationLEDPos[i] < frameLen) frame[stationLEDPos[i]] = ASL_PX_STATION;
      }
    }

    // reconcile the train table into the sprite list: matched trains re-target
    // (gliding there until the next data point is due), new trains fade in,
    // vanished trains fade out (live data after one cycle of grace), and
    // implausible jumps dissolve out+in instead of gliding (junk/reacquired API data)
    void updateTrainSprites(uint32_t nowMs) {
      // glide length: sim positions arrive every refresh; live positions only
      // change when WMATA refreshes, so span the measured feed interval and the
      // train is still moving when its next position arrives
      const uint32_t glideMs = (simModeEnable
                                 ? plotRefreshIntervalMs
                                 : constrain(feedIntervalMs, plotRefreshIntervalMs, (uint32_t)ASL_FEED_MAX_MS))
                               + ASL_GLIDE_SLACK_MS;
      for (auto &s : aslSprites) {
        if (s.mode == ASL_SPR_GHOST && nowMs - s.fadeStartMs >= aslFadeMs()) s.mode = ASL_SPR_FREE;
        s.seen = false;
      }
      // Info panel breakdown of this update's trains
      statFeed = numTrains; statDrawn = statOffMap = statOtherLine = statNonRevenue = 0;
      for (auto &c : statPerLine) c = 0;
      for (uint16_t i = 0; i < numTrains; i++) {
        if (!trainNormal[i]) { statNonRevenue++; continue; }
        int8_t li = aslLineIndex(trainLine[i]);
        if (li < 0) { statOtherLine++; continue; }                 // e.g. Silver, not on this hardware
        float target;
        if (!aslTargetLED(li, trainCircuit[i], target)) { statOffMap++; continue; } // circuit outside the mapped domains
        statDrawn++;
        statPerLine[li]++;
        AslSprite* s = aslFindSprite(li, trainDirection[i], trainId[i]);
        if (!s) {
          aslSpawnSprite(li, trainDirection[i], trainId[i], target, nowMs);
          continue;
        }
        s->seen = true;
        s->missed = 0;
        // live: this train has not moved since its last report (the feed
        // refreshed for other trains) - let its current glide run out
        if (!simModeEnable && fabsf(target - s->targetPos) < 0.01f) continue;
        float cur = aslSpritePos(*s, nowMs);
        if (fabsf(target - cur) <= ASL_TELEPORT_LEDS) {
          s->startPos    = cur;
          s->targetPos   = target;
          s->moveStartMs = nowMs;
          s->moveDurMs   = glideMs;
        } else {
          aslGhostSprite(*s, nowMs);
          aslSpawnSprite(li, trainDirection[i], trainId[i], target, nowMs);
        }
      }
      // a train missing from this cycle's data: live WMATA data often drops a
      // train for one fetch, so it gets one cycle of grace; sim data is exact,
      // so a missing sim train has finished its run and goes immediately
      const uint8_t grace = simModeEnable ? 0 : 1;
      for (auto &s : aslSprites) {
        if (s.mode == ASL_SPR_LIVE && !s.seen && ++s.missed > grace) aslGhostSprite(s, nowMs);
      }
    }

    void plotScenery() {
      clearFrame(RedFrame, sizeof(RedFrame));
      plotStations(RedFrame, sizeof(RedFrame), RedLineStationLEDPosition, RedLineNumStationsInLine);
      clearFrame(BlueFrame, sizeof(BlueFrame));
      plotStations(BlueFrame, sizeof(BlueFrame), BlueLineStationLEDPosition, BlueLineNumStationsInLine);
      clearFrame(GreenFrame, sizeof(GreenFrame));
      plotStations(GreenFrame, sizeof(GreenFrame), GreenLineStationLEDPosition, GreenLineNumStationsInLine);
      clearFrame(OrangeFrame, sizeof(OrangeFrame));
      plotStations(OrangeFrame, sizeof(OrangeFrame), OrangeLineStationLEDPosition, OrangeLineNumStationsInLine);
      clearFrame(YellowFrame, sizeof(YellowFrame));
      plotStations(YellowFrame, sizeof(YellowFrame), YellowLineStationLEDPosition, YellowLineNumStationsInLine);
    }

  public:
    void setup() override {
      aslBuildPerceptLUT(); // usually already built by readFromConfig; harmless to redo
      // fixed IDs (see ASL_FX_*); Yellow must be appended before Status
      aslAddEffect(ASL_FX_RED,    &mode_asl_red,    _data_FX_ASL_RED);
      aslAddEffect(ASL_FX_BLUE,   &mode_asl_blue,   _data_FX_ASL_BLUE);
      aslAddEffect(ASL_FX_GREEN,  &mode_asl_green,  _data_FX_ASL_GREEN);
      aslAddEffect(ASL_FX_ORANGE, &mode_asl_orange, _data_FX_ASL_ORANGE);
      aslAddEffect(ASL_FX_YELLOW, &mode_asl_yellow, _data_FX_ASL_YELLOW);
      aslAddEffect(ASL_FX_STATUS, &mode_asl_status, _data_FX_ASL_STATUS);
      // Draw the scenery before any frame is shown. The frames start zeroed,
      // and pixel code 0 is the TRAIN color slot, so until the first plot
      // every LED of every line lit up in its train color at full preset
      // brightness (for a whole refresh interval after each boot). The boot
      // preset is only applied from the main loop, after this runs.
      plotScenery();
      // run the first data refresh on the first loop instead of one full
      // interval after boot (unsigned wrap-around makes the gate pass at once)
      lastTime = millis() - plotRefreshIntervalMs;
      initDone = true;
    }

    void loop() override {
      if (enabled) updateStatus(); // every pass, so the status LED reacts immediately
      if (!enabled || (strip.isUpdating() && (millis() - lastTime < plotRefreshIntervalMs + 200))) return;
      if (millis() - lastTime < plotRefreshIntervalMs) return;
      lastTime = millis();

      secondOfDay = (realSecondOfDay() + simOffsetS) % 86400UL; // sim clock; offset is 0 unless a test time is set

      if (!delaysRacked) rackTimetables();
      clearTrains();
      feedChanged = false;
      if (simModeEnable) {
        for (uint8_t li = 0; li < ASL_NUM_LINES; li++) {
          offlineSimTrains(li, 0); // Track1
          offlineSimTrains(li, 1); // Track2
        }
      } else if (WLED_CONNECTED) {
        lastFetchMs = millis();
        getWMATAData();
        fetchDurMs  = millis() - lastFetchMs; // how long the blocking fetch froze the loop
      } else {
        fetchResult = FETCH_NO_WIFI;
      }
      plotScenery();
      // live: move trains only when WMATA actually refreshed; unchanged polls
      // and short outages leave them gliding/parked where they are, and only
      // after a minute without good data are they cleared from the map
      const bool liveStale = !simModeEnable && (millis() - lastGoodFetchMs > ASL_FEED_STALE_MS);
      if (simModeEnable || feedChanged || liveStale) updateTrainSprites(millis());
    }

    void addToJsonInfo(JsonObject& root) override {
      JsonObject user = root["u"];
      if (user.isNull()) user = root.createNestedObject("u");
      JsonArray arr = user.createNestedArray(F("ASL trains"));
      arr.add(numTrains);
      arr.add(simModeEnable ? F(" (sim)") : F(" (live)"));

      // AI: below section was generated by an AI
      // Info panel rows. The UI shows value + unit; a row added with a single
      // element shows just the text (an empty unit would print a stray comma).
      // Rows that only apply to one mode are only shown in that mode.
      char buf[112];
      // ArduinoJson stores a const char* as a pointer without copying (it assumes
      // a string literal), but most rows are built in the reused stack buffer
      // below - passing char* makes it copy the text into the document. (Storing
      // the pointer sent random bytes in /json/info and broke the web UI.)
      auto row = [&](const __FlashStringHelper* key, const char* text) {
        JsonArray a = user.createNestedArray(key);
        a.add(const_cast<char*>(text));
      };
      const uint32_t now = millis();

      // ---- clock & RTC (all modes) ----
      // the sim is only as right as WLED's clock, which offline comes from
      // the RTC usermod (or "Set clock from this device")
      const uint8_t src = toki.getTimeSource();
      if (src == TOKI_TS_NONE) {
        row(F("ASL clock"), simModeEnable ? "not set - sim schedule is wrong (needs NTP, RTC or Set clock)" : "not set");
      } else {
        uint32_t sod = realSecondOfDay();
        snprintf_P(buf, sizeof(buf), PSTR("%02u:%02u:%02u ("), (unsigned)(sod / 3600), (unsigned)(sod / 60 % 60), (unsigned)(sod % 60));
        strlcat(buf, (const char*)timeSourceName(src), sizeof(buf)); // ESP32: flash strings are directly readable
        strlcat(buf, ")", sizeof(buf));
        row(F("ASL clock"), buf);
        // offset actually applied (timezone + DST + manual offset): local - UTC
        int32_t off = (int32_t)(localTime - toki.second());
        int32_t m   = (off < 0 ? -off : off) / 60;
        if (m % 60) snprintf_P(buf, sizeof(buf), PSTR("UTC%c%d:%02d"), off < 0 ? '-' : '+', (int)(m / 60), (int)(m % 60));
        else        snprintf_P(buf, sizeof(buf), PSTR("UTC%c%d"), off < 0 ? '-' : '+', (int)(m / 60));
        row(F("ASL UTC offset"), buf);
      }
      if (!ntpEnabled)     row(F("ASL NTP sync"), "disabled");
      else if (!ntpOkSeen) row(F("ASL NTP sync"), "not yet since boot");
      else { formatAge(now - lastNtpOkMs, buf, sizeof(buf)); row(F("ASL NTP sync"), buf); }

      // RTC.chipPresent() is the DS1307RTC library's "chip answered on I2C"
      // flag, updated by the RTC usermod's own reads (at boot and then once a
      // second while it runs) - reading it here causes no I2C traffic
      if (!UsermodManager::lookup(USERMOD_ID_RTC)) row(F("ASL RTC"), "not built in");
      else if (i2c_sda < 0 || i2c_scl < 0)        row(F("ASL RTC"), "off (no I2C pins set)");
      else if (rtcSeen)                            row(F("ASL RTC"), "OK, set the clock at boot");
      else if (RTC.chipPresent())                  row(F("ASL RTC"), "chip found, but its time was not set (NTP or Set clock will set it)");
      else                                         row(F("ASL RTC"), "chip not responding on I2C (check SDA/SCL pins, wiring, chip type DS3231/DS1307)");

      static const char* const stText[] = {
        "red blink: no Wi-Fi and no RTC time", "amber blink: clock not set or no live data",
        "purple: sim on test time", "green: live data OK", "cyan: sim on RTC time", "blue: sim on network time" };
      row(F("ASL status LED"), aslStatus < sizeof(stText) / sizeof(stText[0]) ? stText[aslStatus] : "?");
      row(F("ASL effect IDs"), aslFxIdsOk ? "OK" : "mismatch - presets need updating");

      if (simModeEnable) {
        // ---- sim ----
        const uint32_t sod  = secondOfDay;   // sim clock (includes any test offset)
        const uint32_t open = systemFirstTrainTime, close = systemLastTrainTime;
        const uint32_t opDur = (close > open) ? close - open : 86400UL - open + close; // open == close = 24 h
        const bool inService = ((sod + 86400UL - open) % 86400UL) < opDur;
        if (inService) {
          const uint32_t hw = headwayAt(sod);
          const bool rush = (hw != headwayTimeSeconds);
          snprintf_P(buf, sizeof(buf), PSTR("in service%s, trains every %u:%02u"),
                     rush ? (sod < 43200UL ? ", AM rush" : ", PM rush") : "", (unsigned)(hw / 60), (unsigned)(hw % 60));
        } else {
          char hhmm[6];
          formatHHMM(open, hhmm, sizeof(hhmm));
          snprintf_P(buf, sizeof(buf), PSTR("no departures, next at %s%s"), hhmm, numTrains ? " (last trains finishing)" : "");
        }
        row(F("ASL service"), buf);
        snprintf_P(buf, sizeof(buf), PSTR("RD %u, BL %u, GR %u, OR %u, YL %u min"),
                   (unsigned)((runS[ASL_LINE_RED]    + 30) / 60), (unsigned)((runS[ASL_LINE_BLUE]   + 30) / 60),
                   (unsigned)((runS[ASL_LINE_GREEN]  + 30) / 60), (unsigned)((runS[ASL_LINE_ORANGE] + 30) / 60),
                   (unsigned)((runS[ASL_LINE_YELLOW] + 30) / 60));
        row(F("ASL run times"), buf);
        if (simOffsetS) {
          char hhmm[6];
          formatHHMM((realSecondOfDay() + simOffsetS) % 86400UL, hhmm, sizeof(hhmm));
          snprintf_P(buf, sizeof(buf), PSTR("%s (test time, cleared on reboot)"), hhmm);
          row(F("ASL sim time"), buf);
        }
      } else {
        // ---- live ----
        snprintf_P(buf, sizeof(buf), PSTR("%.1f s (%s)"), feedIntervalMs / 1000.0f,
                   lastFeedChangeMs ? "measured" : "default, not measured yet");
        row(F("ASL feed refresh"), buf);

        char age[32];
        formatAge(now - lastFetchMs, age, sizeof(age));
        switch (fetchResult) {
          case FETCH_NONE:    strlcpy(buf, "not yet", sizeof(buf)); break;
          case FETCH_NO_KEY:  strlcpy(buf, "no API key", sizeof(buf)); break;
          case FETCH_NO_WIFI: strlcpy(buf, "no Wi-Fi", sizeof(buf)); break;
          case FETCH_OK:      snprintf_P(buf, sizeof(buf), PSTR("OK, %s (took %u ms)"), age, (unsigned)fetchDurMs); break;
          case FETCH_PARSE:   snprintf_P(buf, sizeof(buf), PSTR("bad data (parse error), %s"), age); break;
          case FETCH_HTTP:    snprintf_P(buf, sizeof(buf), PSTR("HTTP %d, %s"), fetchHttpCode, age); break;
          default:            snprintf_P(buf, sizeof(buf), PSTR("no connection (%d), %s"), fetchHttpCode, age); break;
        }
        row(F("ASL last fetch"), buf);

        snprintf_P(buf, sizeof(buf), PSTR("%u in feed: %u drawn, %u off-map, %u other lines, %u non-revenue"),
                   statFeed, statDrawn, statOffMap, statOtherLine, statNonRevenue);
        row(F("ASL feed trains"), buf);
        snprintf_P(buf, sizeof(buf), PSTR("RD %u, BL %u, GR %u, OR %u, YL %u"),
                   statPerLine[ASL_LINE_RED], statPerLine[ASL_LINE_BLUE], statPerLine[ASL_LINE_GREEN],
                   statPerLine[ASL_LINE_ORANGE], statPerLine[ASL_LINE_YELLOW]);
        row(F("ASL trains per line"), buf);

        if (lastFeedChangeMs) {
          formatAge(now - lastFeedChangeMs, age, sizeof(age));
          snprintf_P(buf, sizeof(buf), PSTR("positions changed %s"), age);
          row(F("ASL data age"), buf);
        } else {
          row(F("ASL data age"), "no data yet");
        }
        snprintf_P(buf, sizeof(buf), PSTR("%u since boot"), (unsigned)apiCalls);
        row(F("ASL API calls"), buf);
      }
      // AI: end
    }

    // "12 s ago" / "4 min ago" / "3 h ago" for Info panel rows
    static void formatAge(uint32_t ms, char* buf, size_t len) {
      uint32_t s = ms / 1000;
      if (s < 120)        snprintf_P(buf, len, PSTR("%u s ago"),   (unsigned)s);
      else if (s < 7200)  snprintf_P(buf, len, PSTR("%u min ago"), (unsigned)(s / 60));
      else                snprintf_P(buf, len, PSTR("%u h ago"),   (unsigned)(s / 3600));
    }

    // AI: below section was generated by an AI
    // Sim test time, set from the buttons on the usermod settings page (or any
    // JSON client):
    //   {"ASL":{"simAt":"14:30"}}   run the sim as if it were 14:30 now
    //   {"ASL":{"simReset":true}}   back to real time
    // Stored as an offset from the real clock so the sim keeps ticking from the
    // chosen time. Runtime only: not written to cfg.json, cleared by a reboot,
    // and the real clock / RTC chip are never changed.
    void readFromJsonState(JsonObject& root) override {
      JsonObject um = root[F("ASL")];
      if (um.isNull()) return;
      if (um[F("simReset")] | false) simOffsetS = 0;
      const char* at = um[F("simAt")] | (const char*)nullptr;
      if (at) {
        uint32_t target = parseHHMM(at, UINT32_MAX);
        if (target != UINT32_MAX) simOffsetS = (target + 86400UL - realSecondOfDay()) % 86400UL;
      }
      lastTime = 0; // replot on the next loop instead of waiting a refresh interval
    }
    // AI: end

    void addToConfig(JsonObject& root) override {
      JsonObject top = root.createNestedObject(FPSTR(_name));
      top[FPSTR(_enabled)]                = enabled;
      top[F("Enable Train Sim Mode")]     = simModeEnable;
      top[F("Server Address")]            = serverAddress;
      top[F("API Key")]                   = apiKey;
      top[F("Plot Refresh Interval (s)")] = plotRefreshIntervalMs / 1000.0f;
      char hhmm[6];
      formatHHMM(systemFirstTrainTime, hhmm, sizeof(hhmm));
      top[F("System Open Time")]          = hhmm;
      formatHHMM(systemLastTrainTime, hhmm, sizeof(hhmm));
      top[F("System Close Time")]         = hhmm;
      top[F("Train Headway")]             = headwayTimeSeconds / 60.0f;
      top[F("Rush Hour Train Headway")]   = rushHeadwayTimeSeconds / 60.0f;
      formatHHMM(amRushStartTime, hhmm, sizeof(hhmm));
      top[F("Morning Rush Hour Start")]   = hhmm;
      formatHHMM(amRushEndTime, hhmm, sizeof(hhmm));
      top[F("Morning Rush Hour End")]     = hhmm;
      formatHHMM(pmRushStartTime, hhmm, sizeof(hhmm));
      top[F("Evening Rush Hour Start")]   = hhmm;
      formatHHMM(pmRushEndTime, hhmm, sizeof(hhmm));
      top[F("Evening Rush Hour End")]     = hhmm;
      top[F("Fallback Station Dwell (s)")] = stationDwellTimeS;
      top[F("Train Crossfade")]           = aslCrossfade;
      top[F("Hop Below Brightness")]      = aslHopBelowBri;
      top[F("Gamma")]                     = aslGamma;
    }

    bool readFromConfig(JsonObject& root) override {
      JsonObject top = root[FPSTR(_name)];
      bool configComplete = !top.isNull();

      configComplete &= getJsonValue(top[FPSTR(_enabled)], enabled, true);
      configComplete &= getJsonValue(top[F("Enable Train Sim Mode")], simModeEnable, true);
      configComplete &= getJsonValue(top[F("Server Address")], serverAddress);
      serverAddress.trim(); // stray spaces around a pasted URL
      configComplete &= getJsonValue(top[F("API Key")], apiKey);
      // WMATA keys are 32 hex characters and never contain whitespace, so drop
      // all of it (pasted keys often pick up spaces or a line break); runs on
      // every settings save, and WLED re-saves the cleaned value right after
      String key;
      key.reserve(apiKey.length());
      for (size_t i = 0; i < apiKey.length(); i++)
        if (!isspace((unsigned char)apiKey[i])) key += apiKey[i];
      apiKey = key;

      String hhmm;
      configComplete &= getJsonValue(top[F("System Open Time")], hhmm, "");
      systemFirstTrainTime = parseHHMM(hhmm.c_str(), DEF_OPEN_S);
      configComplete &= getJsonValue(top[F("System Close Time")], hhmm, "");
      systemLastTrainTime  = parseHHMM(hhmm.c_str(), DEF_CLOSE_S);

      float headwayMin = 0.0f;
      configComplete &= getJsonValue(top[F("Train Headway")], headwayMin, 0.0f);
      headwayTimeSeconds = (headwayMin > 0.0f) ? (uint32_t)(headwayMin * 60.0f + 0.5f) : 0;
      if (headwayTimeSeconds == 0) headwayTimeSeconds = DEF_HEADWAY_S; // missing, non-positive, or rounds to zero

      configComplete &= getJsonValue(top[F("Morning Rush Hour Start")], hhmm, "");
      amRushStartTime = parseHHMM(hhmm.c_str(), DEF_AM_RUSH_START_S);
      configComplete &= getJsonValue(top[F("Morning Rush Hour End")], hhmm, "");
      amRushEndTime   = parseHHMM(hhmm.c_str(), DEF_AM_RUSH_END_S);
      configComplete &= getJsonValue(top[F("Evening Rush Hour Start")], hhmm, "");
      pmRushStartTime = parseHHMM(hhmm.c_str(), DEF_PM_RUSH_START_S);
      configComplete &= getJsonValue(top[F("Evening Rush Hour End")], hhmm, "");
      pmRushEndTime   = parseHHMM(hhmm.c_str(), DEF_PM_RUSH_END_S);

      // 0 (or negative) rush headway = rush disabled; missing = default 4 min
      float rushMin = 0.0f;
      configComplete &= getJsonValue(top[F("Rush Hour Train Headway")], rushMin, DEF_RUSH_HEADWAY_S / 60.0f);
      rushHeadwayTimeSeconds = (rushMin > 0.0f) ? (uint32_t)(rushMin * 60.0f + 0.5f) : 0;

      // any open/close combination is valid: close before open wraps past
      // midnight, open == close means 24-hour service

      // whole seconds; used only where no dwell was measured (terminals, data
      // gaps). An empty field arrives as 0, so 0 also means "use the default".
      configComplete &= getJsonValue(top[F("Fallback Station Dwell (s)")], stationDwellTimeS, DEF_DWELL_S);
      if (stationDwellTimeS == 0) stationDwellTimeS = DEF_DWELL_S;
      if (stationDwellTimeS > MAX_DWELL_S) stationDwellTimeS = MAX_DWELL_S;
      // seconds in cfg.json / on the page (decimals ok), milliseconds internally;
      // missing, empty or non-positive = default, minimum 1 s
      float refreshS = 0.0f;
      configComplete &= getJsonValue(top[F("Plot Refresh Interval (s)")], refreshS, DEF_REFRESH_MS / 1000.0f);
      plotRefreshIntervalMs = (refreshS > 0.0f) ? (uint32_t)(refreshS * 1000.0f + 0.5f) : DEF_REFRESH_MS;
      if (plotRefreshIntervalMs < 1000) plotRefreshIntervalMs = 1000;

      configComplete &= getJsonValue(top[F("Train Crossfade")], aslCrossfade, ASL_DEF_CROSSFADE);
      if (!(aslCrossfade >= 0.0f)) aslCrossfade = 0.0f; // also catches NaN
      if (aslCrossfade > 1.0f) aslCrossfade = 1.0f;
      int hopBelow = ASL_DEF_HOP_BELOW; // read as int so out-of-range input clamps instead of wrapping
      configComplete &= getJsonValue(top[F("Hop Below Brightness")], hopBelow, ASL_DEF_HOP_BELOW);
      aslHopBelowBri = (uint8_t)constrain(hopBelow, 0, 255);
      configComplete &= getJsonValue(top[F("Gamma")], aslGamma, ASL_DEF_AA_GAMMA);
      if (aslGamma < 1.0f) aslGamma = 1.0f;
      if (aslGamma > 4.0f) aslGamma = 4.0f;
      aslBuildPerceptLUT(); // gamma may have changed

      delaysRacked = false; // timing settings may have changed; re-rack on next loop
      return configComplete;
    }

    void appendConfigData(Print& settingsScript) override {
      // upgrade the open/close text fields to native HH:MM time pickers;
      // [0] of each named pair is the hidden type field, [1] the visible input
      settingsScript.printf_P(PSTR(
        "for(let n of['System Open Time','System Close Time',"
          "'Morning Rush Hour Start','Morning Rush Hour End',"
          "'Evening Rush Hour Start','Evening Rush Hour End']){"
          "let f=d.getElementsByName('%s:'+n);"
          "if(f[1]){f[1].type='time';f[1].style.width='120px';}}"), _name);
      // AI: below section was generated by an AI
      // Page layout. WLED renders the settings as one flat list in
      // addToConfig() order, so the visual hierarchy is added here:
      //   section heading  - WLED's own group divider (hr.sml) + <h4>
      //   field            - label + input, as rendered by WLED
      //   description      - own line under the input, smaller and dimmed
      // Sections: Data source / Clock / Sim timetable / Train display.
      // Headings are DOM-only, so cfg.json keeps its flat structure. This
      // script runs inside the page's GetV() function: helpers are block-scoped
      // and the button handlers are attached to window.
      //   ai(field, text)  description under a field (wraps WLED's addInfo)
      //   hd(field, html)  insert html above a field's label
      //   sec(title)       section heading html
      settingsScript.printf_P(PSTR(
        "{let p='%s:',"
        "ds='<span style=\"display:inline-block;font-size:80%%;line-height:1.4;opacity:.75\">',"
        "ai=(n,t)=>addInfo(p+n,1,'<br>'+ds+t+'</span>'),"
        "hd=(n,h)=>{let e=d.getElementsByName(p+n)[0];if(e&&e.previousSibling){let v=cE('div');v.innerHTML=h;e.parentNode.insertBefore(v,e.previousSibling);}},"
        "sec=t=>'<hr class=\"sml\"><h4>'+t+'</h4>';"), _name);
      settingsScript.print(F(
        // clock status and actions: status comes from this usermod's
        // /json/info rows; "Set clock" sends the same {"time":...} the main UI
        // sends (the RTC usermod then writes it to the chip); the sim test
        // time goes to readFromJsonState and never touches the real clock
        "window.aslU=()=>fetch(getURL('/json/info')).then(r=>r.json()).then(j=>{"
          "let u=j.u||{},c=u['ASL clock'],s=u['ASL sim time'];"
          "gId('aslS').innerHTML='Device time: <b>'+esc(c?c.join(''):'?')+'</b>'+(s?'<br>Sim time: <b>'+esc(s.join(''))+'</b>':'');"
        "}).catch(()=>{});"
        "window.aslP=o=>fetch(getURL('/json/state'),{method:'POST',headers:{'Content-Type':'application/json'},"
          "body:JSON.stringify(o)}).then(()=>setTimeout(aslU,500)).catch(()=>{});"
        "window.aslClock=()=>aslP({time:Math.floor(Date.now()/1000)});"
        "window.aslApply=()=>{let v=gId('aslTm').value;if(v)aslP({ASL:{simAt:v}});};"
        "window.aslReal=()=>aslP({ASL:{simReset:true}});"

        // section headings (the Clock section sits between Data source and
        // Sim timetable, so it is inserted together with the next heading)
        "hd('Enable Train Sim Mode',sec('Data source'));"
        "hd('System Open Time',sec('Clock')+"
          "'<div id=\"aslS\">Device time: ...</div>"
          "<button type=\"button\" class=\"sml\" onclick=\"aslClock()\">Set clock from this device</button><br>"
          "Sim test time <input type=\"time\" id=\"aslTm\" style=\"width:120px\">"
          "<button type=\"button\" class=\"sml\" onclick=\"aslApply()\">Apply</button>"
          "<button type=\"button\" class=\"sml\" onclick=\"aslReal()\">Real time</button><br>'"
          "+ds+'Test time changes the sim only: not saved, cleared on reboot, real clock and RTC untouched.</span>'"
          "+sec('Sim timetable'));"
        "hd('Train Crossfade',sec('Train display')+ds+'Trains fade in and out over WLED\\'s Transition Time (Config &gt; LED Preferences).</span>');"

        // field descriptions
        "ai('Enable Train Sim Mode','on = offline timetable, off = live WMATA positions');"
        "ai('Server Address','live mode only; the API key is appended automatically');"
        "ai('API Key','WMATA key, only used in live mode');"
        "ai('Plot Refresh Interval (s)','data refresh and glide time, seconds (decimals ok); live mode: 15 or more recommended, WMATA updates each train about every 15 s');"
        "ai('System Close Time','earlier than open = service past midnight; equal = 24h');"
        "ai('Train Headway','minutes between departures (decimals ok)');"
        "ai('Rush Hour Train Headway','minutes between departures in rush windows (0 = no rush service)');"
        "ai('Morning Rush Hour End','rush windows are same-day; start at/after end disables one');"
        "ai('Fallback Station Dwell (s)','whole seconds; dwell at terminals and stations with no measured time (blank = 25)');"
        "ai('Train Crossfade','LED-to-LED handover, fraction of an LED: 0 = hop, 1 = full blend');"
        "ai('Hop Below Brightness','below this brightness (0-255, incl. segment opacity) trains hop instead of crossfading; 0 = never');"
        "ai('Gamma','brightness curve of the crossfade, 1 = linear');"
        "aslU();"
        "}"));
      // AI: end
    }

    uint16_t getId() override { return USERMOD_ID_UNSPECIFIED; }
};

const char UsermodASL::_name[]    PROGMEM = "ASL-usermod-v2";
const char UsermodASL::_enabled[] PROGMEM = "enabled";

static UsermodASL asl_usermod;
REGISTER_USERMOD(asl_usermod);
